### ISSUE TITLE
Last push broke things.... :)

### ISSUE THREAD

**Issue by bernatgy** [yairEO/tagify#10]
[https://github.com/yairEO/tagify/commit/1ca0945070fc009432097647bf994eea69fe599a](https://github.com/yairEO/tagify/commit/1ca0945070fc009432097647bf994eea69fe599a)

**Line 162:** || _should be_ &&
Every single character is added separately right now.

**Comment by yairEO** [comment]
ha crap. I work exclusively on FF and everything always works great there :)
as always, Chrome makes problems... will be fixed, thank you very very much for reporting!

**Comment by bernatgy** [comment]
Well... This. Confirmed interestingly works on FF, but to be honest, it shouldn't... :)

**Comment by yairEO** [comment]
why do you think it shouldn't work on FF? does the spec say an input filled via a datalist option should be the same as a regular `input` event? if so, that is a troubling spec choice because I have no way of knowing if an input was pasted / typed / chosen from datalist

I need to know in order to automatically add the chosen datalist option as a tag

**Comment by bernatgy** [comment]
I didn't actually read the code, so I don't know. This is the way I approached it:
fromDataList // If the event is a character.
this.addTag() // If (fromDataList)

So it really is simply adding every character input. This way, it should have been bugging on FF too IMO. But this is just a ....................

> Ooookay, let's just thrash my understanding. I was wrong, it should have been working on chrome. It's....  I missed that exclamation mark! :D
