### ISSUE TITLE
Changing Writing Direction Breaks

### ISSUE THREAD

**Issue by gl0dt** [yairEO/tagify#1000]
**Issue Description
Changing direction from LTR to RTL in browser breaks 
* The content to parts
* Adding unexpected line ending
* This is also causing `onChange` callback returning a few line endings

**Reproduction steps:
1. Go to this example [Mix Text & Tags](https://yaireo.github.io/tagify/#section-mix)
2. Write click on the input and select **Writing Diection** > **Right to Left**
3. Observe the broken text and new lines added.

**Comment by yairEO** [comment]
Please state your OS/Browser and add a video showcasing the issue. I see no problem with `Windows10/Chrome 99`

**Comment by gl0dt** [comment]
I'm using `macOS Monterey/Chrome 99`
Attaching a [screen recording](https://github.com/yairEO/tagify/files/8364444/Missing.Value.and.unexpected.new.line.when.changing.writing.direction.webm.zip) of your React live example that shows:
1. Newline is added when changing to RTL lang.
2. Changing back to LTR doesn't restore the original content
3. The `onChange` gets triggered when changing the writing direction from LTR to RTL and the returned value is missing some content, in this example it's missing `(Only tags from the whitelist are allowed. Whitelist contains names of Southpark characters.)
(Open this demo in a full-window to be able to type new-line returns)`

**Comment by yairEO** [comment]
There is technically no point in changing the language from one to another (mixing LTR with RTL)
because this is a chrome-thing, as it wraps the changed language direction text with some HTML to push it to the other side, and this is not something that tagify exposes to the output and will not be (and cannot) be saved on your server, which then, on page refresh, will loose the alignment of the language.

This is more for here-and-now styling which will not be saved anyway, but can be useful as a visual aid.

I'm unsure how that the `onChange` event is fired is causing you problems, but I will fix it so the text, which was changed its lang direction, will be included.
