### ISSUE TITLE
Trigger dropdown

### ISSUE THREAD

**Issue by davide-lucchelli** [yairEO/tagify#102]
Hi,
is there a way to show the dropdown before writing any character (pressing down button or clicking on the input)?

Thanks,
Davide

**Comment by davide-lucchelli** [comment]
Wow! Already done? Awesome! Thank you so much!!!

**Comment by cf-git** [comment]
Please, edit tagify.js
in "Dropdown controller" (dropdown.show)
replace 
```javascript

                var listItems, listHTML;
                if (!this.settings.whitelist.length || !this.settings.dropdown.enablede) return; // if no value was supplied, show all the "whitelist" items in the dropdown
                // @type [Array] listItems
```
to
```javascript
                var listItems, listHTML;
                if (!this.settings.whitelist.length || this.settings.dropdown.enabled === false) return; // if no value was supplied, show all the "whitelist" items in the dropdown
                // @type [Array] listItems
```

because focus trigger work but not show white list

**Comment by davide-lucchelli** [comment]
Ok, thanks :)

**Comment by tuhinhossain** [comment]
`var input = document.getElementById('colorFilter');
       var tagify=new Tagify(input,{
            whitelist : ['red', 'blue', 'green', 'yellow', 'white', 'black', 'pink', 'orange'],
            dropdown:{
                enabled: 0
            }
});`

I have tried with this code but not working, When I add `  enabled: 1` then it works for one keyboard press. Please help

**Comment by yairEO** [comment]
I will fix this today

**Comment by kojita** [comment]
Please.

If you use ".addTags ()" except initialization,
You can ignore whitelists and add,
Even if it is on the list it can not be added.
That is the previous behavior,

Addition of ".addTags ()",
It changes with the behavior of deletion with the button.

Do I have to use ".addTags ()" other than initialization?

Using ".addTags ()" For example,
I want to add from there.

Even v2.8.6

**Comment by kojita** [comment]
Please.

If you use ".addTags ()" except initialization,
You can ignore whitelists and add,
Even if it is on the list it can not be added.

That is the previous behavior,
Addition of ".addTags ()",
It changes with the behavior of deletion with the button.

Do I have to use ".addTags ()" other than initialization?

Using ".addTags ()" For example,
I want to add from there.

It is also v 2.8.6 !.

**Comment by yairEO** [comment]
@kojita - I'm sorry I do not understand at all..

**Comment by kojita** [comment]
Thank you for your reply.

And I am sorry to have trouble

https://yaireo.github.io/tagify/
Than

TAGS WITH PROPERTIES Improved

We send selected strings to one side using two Tagify.


When the story is long, it seems to be unnecessary to understand, so I will only describe the main points.

※
tagifyArray_wiew.addTags(tagifyArray_insert[nowTagNameId+'-insert'].settings.whitelist);



In the above, we just put one Tagfiy string in the other.

The rules whitelist is identical.

Repeating that, for some reason, despite prohibiting duplication,
Duplicate after erased operation.

In addition, you can not register next after erasing.



Although I am on bootstrap and Smarty convenience, I do not put all of html


					<div class="countries" id="{$oneList['resource_type']}-{$oneList['unique_id']}"></div>

					<div class="countries" name="{$oneList['resource_type']}-{$oneList['unique_id']}-insert"></div>

Looping with two of them, just making the same kind of things.


Although I can read English,
I can not write the sentences well.

This sentence uses translation.

Because it might not go well, I made an animation.
https://vimeo.com/306014391


Thank you for listening to the story
---------------------------------------------------------------------------------------------------------
<style>

.tagify {
	display: block !important;
}

.tagify__dropdown.extra-properties .tagify__dropdown__item > img{
	display: inline-block;
	vertical-align: middle;
	height: 20px;
	transform: scale(.75);
	margin-right: 5px;
	border-radius: 2px;
	transition: .12s ease-out;
}

.tagify__dropdown.extra-properties .tagify__dropdown__item:hover > img{
	transform: none;
	margin-right: 12px;
}

.tagify.countries .tagify__input{
	min-width:175px;
	right: 0.2em !important;
	top: 0.65em !important;
}

.tagify.countries tag{ /* white-space:nowrap; */ }
.tagify.countries tag img{
	display: inline-block;
	vertical-align: middle;
	height: 16px;
	margin-right: 3px;
	border-radius: 2px;
}

.tagify__input tag {
	margin: auto 2.5px !important;
	padding: 5px;
}

.tagify tag>div {
	position: relative !important;
	display: inline !important;
	width: auto !important;
}

</style>
<script>
window.onload=function(){

	var tagifyArray_insert={};
	var tagifyArray_wiew;
	var nowTagNameId;

	for(var oneList in inputSourceList){

		nowTagNameId=inputSourceList[oneList]['resource_type']+'-'+inputSourceList[oneList]['unique_id'];

// 		var all_column_name = document.getElementById(nowTagNameId);

// 		for(var oneData in inputSourceList[oneList]['data']){

// 			var apendTagObj=document.createElement('tag');
// // 			apendTagObj.id='img_address_insert_mark';
// // 			apendTagObj.className='tagify_dummy_all';
// // 			apendTagObj.style.width='16px';
// // 			apendTagObj.style.height='16px';
// // 			apendTagObj.style.position='absolute';
// //			apendTagObj.style.top='0px';
// // 			apendTagObj.style.margin='-12px 0 0 -4px';

// 				var apendDivObj=document.createElement('div');

// 					var apendIObj=document.createElement('i');
// 					apendIObj.className='fa fa-code-fork';
// 				apendDivObj.appendChild(apendIObj);

// 					var apendSpanObj=document.createElement('span');
// 						var apendTextObj=document.createTextNode(inputSourceList[oneList]['data'][oneData]['value']);
// 					apendSpanObj.appendChild(apendTextObj);
// 				apendDivObj.appendChild(apendSpanObj);
// 			apendTagObj.appendChild(apendDivObj);
// 			all_column_name.appendChild(apendTagObj);

// 		}
console.log(nowTagNameId);
tagifyArray_insert[nowTagNameId+'-insert'] = new Tagify(document.querySelector('div[name='+nowTagNameId+'-insert'+']'), {
			delimiters : null,
			tagTemplate : function(v, tagData){
			return `<tag title='${ v }'>
							<x title=''></x>
							<div>
								<img onerror="this.style.visibility = 'hidden'" src='https://lipis.github.io/flag-icon-css/flags/4x3/${ tagData.code.toLowerCase() }.svg'>
								<span class='tagify__tag-text'>${ v }</span>
							</div>
						</tag>`;
			},
			enforceWhitelist : true,
			whitelist : inputSourceList[oneList]['data'],
			dropdown : {
				enabled: 1, // suggest tags after a single character input
				classname : 'extra-properties', // custom class for the suggestions dropdown
				itemTemplate : function(tagData){
				return `<div class='tagify__dropdown__item ${ tagData.class ? tagData.class : "" }'>
								<img onerror="this.style.visibility = 'hidden'"
									 src='https://lipis.github.io/flag-icon-css/flags/4x3/${ tagData.code.toLowerCase() }.svg'>
								<span>${ tagData.value }</span>
							</div>`
				}
			},
			mapValueToProp : "code", // map tags' values to this property name, so this property will be the actual value and not the printed value on the screen
		});

console.log(tagifyArray_insert[nowTagNameId+'-insert']);


		tagifyArray_insert[nowTagNameId+'-insert'].on('remove', function(e){
			console.log(e, e.detail);
		});

		tagifyArray_insert[nowTagNameId+'-insert'].on('add', function(e){
			console.log( tagifyArray_insert[nowTagNameId+'-insert'].DOM.originalInput, tagifyArray_insert[nowTagNameId+'-insert'].DOM.originalInput.value);
		});

		// add the first 2 tags from the "allowedTags" Aray automatically
// 		tagifyArray_insert[nowTagNameId+'-insert'].addTags(tagifyArray_insert[nowTagNameId+'-insert'].settings.whitelist.slice(0,2));

// 		console.log(tagifyArray_insert[nowTagNameId+'-insert'].settings.whitelist.slice(0,2));
// 		console.log(tagifyArray_insert[nowTagNameId+'-insert'].settings.whitelist.slice(0,-1));
// 		console.log(tagifyArray_insert[nowTagNameId+'-insert'].settings.whitelist);

		var tagifyInitDomPointObj=document.querySelector('div[name='+nowTagNameId+'-insert'+']');
		//今のバージョンのTagify は、入力を促す設定の文言を出す術が載ってない？無い？ので追加した
		tagifyInitDomPointObj.previousElementSibling.getElementsByClassName('tagify__input')[0].setAttribute('data-placeholder','追加したいカラム名を順に記述し「Enter」でも入力可能です');


		console.log('div[name='+nowTagNameId+']');
		//console.log(inputSourceList[oneList]['unique_id']);

		tagifyArray_wiew = new Tagify(document.getElementById(nowTagNameId), {
// 		var tagifyArray_wiew = new Tagify(document.querySelector('div[name='+nowTagNameId+']'), {
			delimiters : null,
			tagTemplate : function(v, tagData){
			return `<tag title='${ v }'>
							<x title=''></x>
							<div>
								<img onerror="this.style.visibility = 'hidden'" src='https://lipis.github.io/flag-icon-css/flags/4x3/${ tagData.code.toLowerCase() }.svg'>
								<span class='tagify__tag-text'>${ v }</span>
							</div>
						</tag>`;
			},
			enforceWhitelist : true,
			whitelist : inputSourceList[oneList]['data'],
			dropdown : {
				enabled: 1, // suggest tags after a single character input
				classname : 'extra-properties', // custom class for the suggestions dropdown
				itemTemplate : function(tagData){
				return `<div class='tagify__dropdown__item ${ tagData.class ? tagData.class : "" }'>
								<img onerror="this.style.visibility = 'hidden'"
									 src='https://lipis.github.io/flag-icon-css/flags/4x3/${ tagData.code.toLowerCase() }.svg'>
								<span>${ tagData.value }</span>
							</div>`
				}
			},
			mapValueToProp : "code", // map tags' values to this property name, so this property will be the actual value and not the printed value on the screen
		});

		tagifyArray_wiew.on('remove', function(e){
			console.log(e, e.detail);
		});

		tagifyArray_wiew.on('add', function(e){
// 			console.log( tagifyArray_wiew.DOM.originalInput, tagifyArray_wiew.DOM.originalInput.value);
		});

		// add the first 2 tags from the "allowedTags" Aray automatically
		tagifyArray_wiew.addTags(tagifyArray_insert[nowTagNameId+'-insert'].settings.whitelist);

// 		console.log(tagifyArray_wiew.settings.whitelist.slice(0,2));
// 		console.log(tagifyArray_wiew.settings.whitelist.slice(0,-1));
// 		console.log(tagifyArray_wiew.settings.whitelist);


console.log(document.getElementById(nowTagNameId).previousElementSibling.getElementsByClassName('tagify__input')[0]);
		var tagify_wiewInitDomPointObj=document.getElementById(nowTagNameId);
		//今のバージョンのTagify は、入力を促す設定の文言を出す術が載ってない？無い？ので追加した
		tagify_wiewInitDomPointObj.previousElementSibling.getElementsByClassName('tagify__input')[0].setAttribute('data-placeholder','追加したいカラムをクリックすると「使いたいカラムを選択」に入力されます');

		var tagsAll=tagify_wiewInitDomPointObj.previousElementSibling.children;
		console.log(tagsAll);

		Array.prototype.forEach.call(tagsAll,function( item ) {
// 		Array.prototype.slice.call(tagsAll).filter(function(item, index, all) { /* console.log(item.hasAttribute("title")); */ return item.hasAttribute("title"); }).forEach(function(item) {

// console.log(item);
// 			item.getElementsByTagName('x').style.visibility = "hidden";
//console.log(item.getElementsByTagName('x')[0]);
			if(typeof item.getElementsByTagName('x')[0] !=='undefined'){
				item.getElementsByTagName('x')[0].parentNode.removeChild(item.getElementsByTagName('x')[0]);
// 				item.getElementsByTagName('x')[0].style.display = "none";
// console.log(item);

// 				$(item).click(function() {
// 					tagifyArray_insert[nowTagNameId+'-insert'].addTags($(this).text().trim());

// 					console.log($(this).text().trim());
// 					console.log($(this).contents().filter(function() {
// 						  return this.nodeType == Node.TEXT_NODE;
// 					}).text());
// 				});

				item.addEventListener(
				"click"
				,function(env){

console.log(tagifyArray_insert);

					if(env.target.hasChildNodes() && env.target.childNodes[0].nodeType==3){

						if(env.target.childNodes[0].nodeValue.trim()=='' && env.target.childNodes[0].nodeValue===null){
						}else{
							if(env.target.tagName=='DIV'){
								console.log(env.target.parentNode.parentNode.nextElementSibling.id, env.target.tagName, env.target.getElementsByTagName('span')[0].childNodes[0].nodeValue);
								tagifyArray_insert[env.target.parentNode.parentNode.nextElementSibling.id+'-insert'].addTags(env.target.getElementsByTagName('span')[0].childNodes[0].nodeValue);
							}else{	//span
								console.log(env.target.parentNode.parentNode.parentNode.nextElementSibling.id, env.target.tagName, env.target.childNodes[0].nodeValue);
								tagifyArray_insert[env.target.parentNode.parentNode.parentNode.nextElementSibling.id+'-insert'].addTags(env.target.childNodes[0].nodeValue);
							}


							env.stopPropagation();
							return false;
						}
					}else{
						console.log(env.target.parentNode.parentNode.parentNode.nextElementSibling.id, env.target.tagName, env.target.nextElementSibling.childNodes[0].nodeValue);
						tagifyArray_insert[env.target.parentNode.parentNode.parentNode.nextElementSibling.id+'-insert'].addTags(env.target.nextElementSibling.childNodes[0].nodeValue);
					}
				}
				,false
				);


			}
		});

	}
}
</script>

**Comment by kojita** [comment]
Although I can read English,
I can not write the sentences well.

**Comment by yairEO** [comment]
@kojita - Thanks, that animation helps me to better understand the problem.

So clicking on tags from one list should add them to the other Tagify, but then things starts to get crazy, after deleting and re-adding the same tags.

I will investigate this, Thanks again for reporting!

**Comment by kojita** [comment]
It worked properly.
Thank you for the new version!

**Comment by yairEO** [comment]
[Working demo](https://jsbin.com/pofewut/1/edit?html,js,output)
