### ISSUE TITLE
When you autocomplete from whitelisted list, possibility to add it straight as tag still not working

### ISSUE THREAD

**Issue by ElvenDev** [yairEO/tagify#11]
Apparently, it is still not working. When I select a tag from whitelist (I start typing and then select or press enter), it won't be added to a tag list, still, have to double enter, to add it.

Related to issue #8

Thanks for the tagify & for the addition/fixes!

**Comment by yairEO** [comment]
Yes technically Javascript cannot know if a `datalist` option was selected, there is no event for that.

It would be best if I would create the suggestions list myself instead of using the `datalist` element, but it would require time, since this is not an easy thing to to, and will sadly bloat the code

**Comment by ElvenDev** [comment]
I haven't really dived into your code yet, so I cannot comment if it is hard or not (Might do it later, as I need this fix for my project), but don't you have the suggestion list already as whitelist variable? This case only happens when you have an actual list where you select value (autocomplete).

**Comment by yairEO** [comment]
I will try to make a fix in a few days, when I get to it, promise
