### ISSUE TITLE
When running .removeTag() in a loop .value gets messed up

### ISSUE THREAD

**Issue by it-xtech-dev** [yairEO/tagify#113]
When running `.ramoveTag()` multiple times one after another `.value` property is not properly updated. The reason is that in some conditions `.removeTag()` releases control when tag element still exists so next running .removeTag() will operate over obsolete index. This is the consequnce of how transition handling is implemented. The only way to bypass this problem is to disable transition by setting its duration to 0 => `.remove(Tag,false,0)`;

Behavior can be reproduce in this example:
https://jsbin.com/jirokirexu/2/edit?html,js,console,output

**Comment by yairEO** [comment]
You need to call `removeTag` without the animation. This is why you get this value, because you are firing `removeTag` as fast as possible, one after the other, and the code is expecting an animation to be finished in order to update the value.

I will see what I can do, but if you looked at the [source-code](https://github.com/yairEO/tagify/blob/master/src/tagify.js#L665) you would see that the method accepts a flag for the animation so you should write it as:

    this.removeTag(tagElement, false, 0);

**Comment by it-xtech-dev** [comment]
Got it!

I this docs should mention this case. By the way, are there any requirements to join this project development?

**Comment by yairEO** [comment]
No, no requirements, do you want to contribute?
I'm not sure what's there to do more than there is already, it's working quite well and has wide-range of features.

The most important things for me is to keep it slim and with good code quality, but slim is the top priority since so many scrips are there are bloated..
