### ISSUE TITLE
Ability to insert the tags html element after the original input

### ISSUE THREAD

**Issue by dumbasPL** [yairEO/tagify#1130]
It's currently [hard coded](https://github.com/yairEO/tagify/blob/master/src/tagify.js#L301) to inset before the original input. Would be nice if we could somehow decide where to insert it (before/after).

This is useful when using something like [Bootstrap's input group](https://getbootstrap.com/docs/5.2/forms/input-group/) where the CSS rounds only the first and last element while leaving other edges square. With the current behavior, the least element is the invisible original input. The actual visible lest input is the `tags` tag but it doesn't get rounded since it's not actually last.

**Comment by dumbasPL** [comment]
> This will break other things.
Like? Can't we just set the default value so it matches the current behavior or does something else rely on the specific order?

> Please post a jsbin demo [...] so I could assist further
I don't need assistance, I already fixed it in CSS for the time being.  
This is a feature request, not a help request.

If it would really be a breaking change then I guess I'll have to live with a CSS hack.

**Comment by yairEO** [comment]
I wanted to help in finding the best way to tackle this with CSS selectors.

Injecting Tagify after the original input (and not before) will force me add some attribute or class to the original input, in order to hide it. and will probably break other things which I cannot come up with at the moment, as Tagify is a mega-complex component, which took me years to build.. and I'm still working on it, since there are constant bugs flowing in from users. it's just crazy how complex it is :)

**Comment by dumbasPL** [comment]
got it, thanks
