### ISSUE TITLE
getPersistedData with jquery tagify

### ISSUE THREAD

**Issue by gidzr** [yairEO/tagify#1171]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Hi Yair, just wondering if getPersistedData works with the jquery version 

eg. $(inputId).data('tagify').getPersistedData(uniqueId)  //<-- this throws an error.

Also wondering if getPersistedData is required when a unique "id" is already added for new Tagify({id:'uniqueId'}) to restore selected tags after a page refresh? or whether it's automated via the unique id?

I've actually set up a complex retrieval process from setLocalStorage, and if I can delete that code in favour of something built-in, that would be my preference.

Cheers!

**Comment by yairEO** [comment]
Why are you calling `.getPersistedData(uniqueId)`?

Everything is automatic as long as you initialize your Tagified components using the exact same ids, see this README section:
https://github.com/yairEO/tagify#persisted-data

**Comment by gidzr** [comment]
Hi Yair! I am thinking that the persisted-data initialised with same ids (that you link above), is related to the getPersistedData/setPersistedData in the Methods section.

I thought that it would be possible to call the persisted data, so I can use it to trigger downstream items.

ie. Currently my understanding is that the persisted data helps to populate the tagify field when onscreen which I could access with (#tagID).val(). But if I wanted to access persisted data of a tagify that's not onscreen, I could access it with the getPersistedData method.  Is this not the case?

Cheers

**Comment by yairEO** [comment]
Well, you are the owner of your website/app data, and you should have access to everything, regardless if you are using Tagify or any other visual tags component.

I do not recommend relying on Tagify to get any data from another field. You should act as if Tagify does not exist at all, and you are working with pure data. Ignore Tagify.

Yes you can use the `getPersistedData` method, and I've exposed it, but I don't really see a use case for it...

The whole idea of persisted-data is due to the async nature of the web - so the user won't have tags disappear in the Tagified component once the field's data has been fetched (via async server request)

**Comment by gidzr** [comment]
Found a workaround, all good :)
