### ISSUE TITLE
Default value on select mode with `searchKeys`

### ISSUE THREAD

**Issue by SofiaSousa** [yairEO/tagify#1176]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/dubojimoyi/edit?html,js,output

### Explanation

- **What is the expected behavior?**
The Initial value of the select should be the one set for the `tagTextProp` property. (Working fine when searching and listing the dropdown).

- **What is happening instead?**
When setting `searchKeys` prop, the value displayed is not the one for  the `tagTextProp` property, but for the the `value`.

If we inspect, initially we have

```html
<tag title="2" contenteditable="false" spellcheck="false" tabindex="-1" class="tagify__tag tagify--noAnim" label="2" value="2">...</tag>
```

then, if we select the same tag manually, we get:

```html
<tag title="2" contenteditable="false" spellcheck="false" tabindex="-1" class="tagify__tag " value="2" label="B">...</tag>
```

`label` attribute gets `value` value and not the `label` value.

**Comment by yairEO** [comment]
This has nothing to do with `select` mode, but is merely a misunderstanding.

You have set the value `2` on the input (as the initial value), and tagify, cannot find such 
a value in the whitelist, and simply prints what you have given it (as value).

The reason Tagify does not "know" there is a whitelist item with a value of "2", 
is because you've overwritten the default `searchKeys` dropdown setting and neglected to maintain
the key "value" there, for Tagify to also look for items with that key:

```
searchKeys: ['label', 'value']
```

**Comment by SofiaSousa** [comment]
It doesn't solve the issue because we don't want to search by the `value`, only by the `label`. 

Why Tagify can find the default value if `searchKeys` are not set? It doesn't seem coherent.

If the `whitelist` has an ID and a Name, how could we set up a select which has the ID as default value and but displays the Name (the with dropdown showing Names and searching by Name) ?
