### ISSUE TITLE
Transform pasted text into tags or transform when writing a tag

### ISSUE THREAD

**Issue by wayheming** [yairEO/tagify#1213]
Hello, is it possible to follow the text and immediately convert it when the tag ends? And also start this mechanism when paste text with a tag. For example, I have a `mixTagsInterpolator: ["&", "|"],` and I write the following text `test text &some_tag_1` and after I put the symbol `|` I want it to be immediately converted into a tag or after paste the text, for example `&kenny| test text`.

**Comment by yairEO** [comment]
`mixTagsInterpolator` is not for typing. It's for parsing pre-existing data which brought by the server (for example) and it is the value in the "original" (hidden) input/textarea field.

A user does not know and should not write interpolated text. 

What you want is a use case which I never considered, which is creating new tags on-the-fly, while typing, without them being necessarily be in a whitelist.

You need to find very unique-characters for the user to type. My default ones that I put are much better than yours, because they make more sense and they are also double-sides.

If you are using the pattern `pattern: /@/` for example, then it's pretty fast to type `@` then some tag and then hit <kbd>Keydown</kbd> and <kbd>Enter</kbd> to convert it to a tag.

It is indeed more tricky when pasting..

**Comment by wayheming** [comment]
Hi @yairEO  thanks for the reply it partially works if I use `parseMixTags` but there is a problem with the cursor it always jumps to the beginning because I replace all the content, maybe you have some thoughts on this?

```js
var input = document.querySelector('[name=mix]'),
tagify = new Tagify(input, {
	mixTagsInterpolator: ["{", "}"],
	mode: 'mix',
	duplicates: true,
	originalInputValueFormat: function(valuesArr){
		return valuesArr.value
	},
});

tagify.on('input', function(e){
	let tags = tagify.value;
	let content = e.detail.textContent;

	tags.map(function(item){
		content = content.replace(item.value, '{' + item.value + '}');
	});

	tagify.removeAllTags();
	tagify.parseMixTags(content)
})

```

**Comment by yairEO** [comment]
The last *selection* object is stored in `tagify.state.selection` so after executing `tagify.parseMixTags(content)` you can use that information to place the caret where it was.

Try this method for setting the caret place:
https://developer.mozilla.org/en-US/docs/Web/API/Selection/setPosition
