### ISSUE TITLE
How to input 'tag' text and stop removing on blur event in mixedTags

### ISSUE THREAD

**Issue by wowboya** [yairEO/tagify#1227]
Hi. I am using tagify in my project. I am using this by pattern '@' or '#' and selectBox is generated. My problem is that when I use a 'tag' text like '<say-as>~~~</say-as>' in mixedTags and click the other component(blur event on), tag disappears.

Here is an example:

Before blur event
![image](https://github.com/yairEO/tagify/assets/72731543/3fd52118-f89b-44ed-b807-0180d7942abe)

After blur event
![image](https://github.com/yairEO/tagify/assets/72731543/4cc00f6d-47c0-4623-a555-79876d7f4753)

I tested version(4.17.8) but checked the same problem.

please help me :)

**Comment by yairEO** [comment]
I'm sorry but I don't understand. can you please provide a minimal live demo example by modifying this
jsbin and paste it here? https://jsbin.com/jekuqap/edit?html,js,output

**Comment by yairEO** [comment]
Closed due to unresponsiveness from reporter and I don't understand the question

**Comment by FreshDoktor** [comment]
Hi :) I have the same problem and a working js bin for the problem. It seems like something in the method “loadOriginalValues” removed text that starts with the < char. You can see the input should contain the text <not-here> but the text is missing. Also if you try to input any text that include <something> this whole part will be missing if the text is put into the method after onChange. 



At this moment jsbin is unfortunately down after I tried to save the demo, but I was able to copy the js of the minimal live demo html was unchanged. 

```
var input = document.querySelector('input')
var tagify;
tagify = new Tagify(input, {
  mode: 'mix',
    editTags: false,
    pattern: /\$/,
    tagTextProp: 'text',
    placeholder: this.placeHolder,
    backspace: true,
    autoComplete: {
      enabled: true,
      rightKey: true
    },
    mixMode: {
      insertAfterTag: ''
    },
    dropdown: {
      enabled: 1,
      position: 'text',
      mapValueTo: 'text',
      highlightFirst: true
    },
  callbacks: {
    change: (event) => {
      tagify.loadOriginalValues(event.detail.value)
    }
  }
})

tagify.on('change', console.log)

tagify.loadOriginalValues('here <not-here> also here')
```

I need to call this method because I need to map between your tags within the string to a different format that our backend can work with (and vice versa). So I need this call so that I can get a string from the backend, map it and then put it back into the input field.

Maybe there is a workaround so i can update the input without this method? 

For Example: 
Backend is sending String -> "User (${User}) is using this Input."
And the loadOriginalValues is getting this resolved string -> "User ([[{"id":1957,"value":"User","title":"U00000","prefix":"$"}]]) is using this Input."

I hope this is enough info, if not feel free to ask. :) Thanks in advance
