### ISSUE TITLE
Delay of 100ms before event.detail.tagify.DOM.originalInput.tagifyValue gets updated

### ISSUE THREAD

**Issue by suzumejakku** [yairEO/tagify#1240]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation

- **What is the expected behavior?**
Immediate update of ```event.detail.tagify.DOM.originalInput.tagifyValue```

- **What is happening instead?**
I recently upgraded from 4.16.4 to 4.17.9 and found out this [commit](https://github.com/yairEO/tagify/commit/cff6a1b48c002b70b0694b8f763441c07552807f) introduced a delay of 100 ms before the value of ```event.detail.tagify.DOM.originalInput.tagifyValue``` gets updated. 

Here is the context. I am developing an app with Vue and one of my components has a child component which includes tagify. Whenever that child component's tagify gets updated, it $emits an event to the parent component, letting it know what is the new value of tagify. If the user clicks on a save button, that value gets saved into a database. When the user comes back to the page where those components are used, the database is read and the value is set back to tagify for further editing. Of course, I need to save the full details of the content of tagify in order to be able to read it back (I should say 'interpreted') through tagify. As far as I understood (but I could be wrong), the only way to get what I call the 'full details of the content of tagify' is to read ```event.detail.tagify.DOM.originalInput.tagifyValue```. 

In my code I am listening to tagify's input event (via your ```input``` callback), and $emit an update to my parent component with the value of ```event.detail.tagify.DOM.originalInput.tagifyValue```. I spent a couple of hours wondering why it never took into account the latest character I entered. I checked your fix and found out about this 100ms delay. Now, in my callback I have to use a setTimeout for 100ms and then update the parent component. 

Is there another way to obtain the value of tagify's content apart from ```event.detail.tagify.DOM.originalInput.tagifyValue``` with which I would not have to wait for 100ms ?

4.16.4 => this code was working:
```
callbacks: {
   input: (e) => {
      this.$emit('update:modelValue', event.detail.tagify.DOM.originalInput.tagifyValue)
   }
}
```

4.17.x => what I need to do now:
```
callbacks: {
   input: (e) => {
      setTimeout(() => {
         this.$emit('update:modelValue', event.detail.tagify.DOM.originalInput.tagifyValue)
      },100)
   }
}
```

- **What error message are you getting?**
None

**Comment by mariuszste** [comment]
I solved it by adding
```js
callbacks: {
  blur: () => {
    this.$nextTick(() => this.change());
  },
}
```
this makes sure that the value is emitted as soon as the input loses focus. The downside is that without additional checks it will actually be emitted twice. Once from the change event and once from the blur.

but I do agree that using delays is a bad way to do this. I would expect the new value to already be there by the time the input loses focus. We shouldn't need any debouncing mechanisms after the input loses focus since it's value shouldn't change at this point anyway

**Comment by yairEO** [comment]
Please only use the `change` event in such situations (rarely should you listen to `input` event...

**Comment by verheyenkoen** [comment]
I agree with @mariuszste. We're facing the same issue where we transform the value to hidden input fields on change before form submission (as that is how we prefer our backend deals with the incoming data) but the last typed tag is not submitted because on change doesn't fire in time. I agree with debouncing in most scenario's except when blurring the "field".

If not, I guess the delay should at least be configurable so we can disable it (setting to zero might not be enough if that still sets a timeout).
