### ISSUE TITLE
Fuzzy suggest should prioritize the shortest list item instead of making you type the whole thing to bubble it to the top

### ISSUE THREAD

**Issue by atownley** [yairEO/tagify#1250]
When using tags that are variations on things that are more specific, the sort order seems strange (and cumbersome) to do efficient entry without touching the mouse.

Here's a demo: https://jsbin.com/gewatihuba/1/edit?html,js,output

Here's a screenshot:

![image](https://github.com/yairEO/tagify/assets/179614/975cda03-9756-4ca0-b93b-4473acff3427)

Now, I know why it's happening, because the shortest item is in the original whitelist last, and I've seen in the code where you're doing this. So, I guess my suggestion for a fix/implementation would be to additionally sort the temporary filtered list by length, so the shortest match would always be at the top.

Based on using the app I'm building for the last couple of days for data entry and using Tagify for suggestions, this turns out to be quite annoying, and I suspect you can fix/implement it faster than me. ;)

Otherwise, I'm generally happy with the library so far. Thanks for writing it and making it available!

Cheers,

ast

**Comment by atownley** [comment]
So, because it's actually quite annoying for my use case, I've fixed it locally, but in doing so, I learned a couple of things.

It turned out to be easier than I originally thought. I was thinking it was tied to fuzzy match. It's not.

The following lines are were you are setting the items, and it's true regardless of the mode (which I think is correct, and the sort should also be independent of the mode):

This is dropdown.js:
```
63         // TODO: add a Setting to control items' sort order for "listItems"
64         this.suggestedListItems = this.dropdown.filterListItems(value)
```

I added a simple reverse sort function (which you'd already mentioned as a TODO). I would suggest this should be the default behavior however, I realize that the addition of a "sort" option to the dropdown initialization configuration would be more flexible. 

I'd follow your existing approach here, potentially with options for "shortest", "default" and then a function. That way anyone counting on the existing behavior won't be messed up.

However, things got interesting when I was using the one I have in mixed-mode (I have 4 instances per form). Because, further down, you have this:

```
 74         // if "dropdownItemNoMatch" was no defined, procceed regular flow.
 75         //
 76         if( !noMatchListItem ){
 77             // in mix-mode, if the value isn't included in the whilelist & "enforceWhitelist" setting is "false",
 78             // then add a custom suggestion item to the dropdown
 79             if( this.suggestedListItems.length ){
 80                 if( value   &&   allowNewTags   &&   !this.state.editing.scope  &&  !sameStr(this.suggestedListItems[0].value, value) )
 81                     this.suggestedListItems.unshift({value})
 82             }
```

Now, this is an interesting choice. I know why you did it. However, it also depends on what you're trying to do. The problem is when you want to allow *both* the definition of new tags *and* maximize the UX of having the dropdown in the first place.

With the existing code, you have the entered value selected by default since it's a the top of the list. However, if you primarily want to reuse vs. add tags, this isn't great UX. I added a simple (and temporary, while I work out the UX) workaround that used #push vs. #unshift so it's at the end. This prioritizes existing tags, but still allows you to add new ones. It's kinda clunky, but it at least gives the user the option.

In the case of the normal field, the value being typed doesn't appear. They can still add it if they click the mouse, but, again, it depends on the priority of what the users are supposed to do. I can see that both behaviors could be desired, which means that there's actually probably two configuration settings here—or at least some kind of additional hook defined.

What do you think?

**Comment by atownley** [comment]
A follow-up here now that my dataset is getting bigger. It's not enough to sort in just one place. You have to do it twice, because if you don't sort the list of suggestions in #filterListItems, then you won't get to find the shortest suggestions if the maxItems property has been set.

However, the good news is that for regular text fields, I love this component. The fuzzy search is simply *awesome*, and with the two sorting fixes, the usability improves dramatically.

**Comment by yairEO** [comment]
Sorry, I took some time off the computer and didn't want to program or look at Github for months, but now I am back.

I see you're a very smart person and can relate to why I did things in the code in a certain way, and some of my decisions where specific to my views of what is the "best" UX I would want for my myself (if I was a user) and sometimes there is no way of changing that logic without changing the source-code or coming up with new settings.

Regarding the *sort order* - I have forgotten about this and you are right, I was always planning on introducing a setting (under `dropdown` property) which is a function that can return a new (array of suggestions) order, sorted however the developer desires. 

I prefer not to include pre-existing choices because I do not want to inflate Tagify's code with every possible demand that comes up (I get so many requests for random things) but will simply provide a demo of the possibilities (of a custom `sortOrder` setting) in the README file and so developers could copy from that.

The second thing, which is only in `mix-mode` (since in normal mode a user can always add a new tag if that is allowed in the settings) - what is typed by the user is added as the *first* suggestion, which to me makes the most sense but I guess it might be the opposite for others :)

I will think what to do about this. maybe add another setting that controls if it should be added as first or last...

**Comment by atownley** [comment]
Ok. I'll check it out and see if I can manage this. I've a version I've been using with the modification I suggested since I entered this. I couldn't use it the way it was, but I'm not in development mode at the moment, so it might take some time. Thanks for addressing this issue.
