### ISSUE TITLE
Editing text with HTML elements in mixed mode strips HTML from textarea value

### ISSUE THREAD

**Issue by atownley** [yairEO/tagify#1252]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/vosemehoja/1/edit?html,js,console,output

***React*** issue template:
https://codesandbox.io/s/tagify-react-issue-template-4ub1r?file=/src/index.js

### Explanation

- **What is the expected behavior?**

I would expect that it wouldn't strip the links. Based on the way I am using Tagify, I'd ideally like to have a way to transform the links into tags, but I haven't figured that out yet. However, having the content stripped of HTML isn't going to work.

- **What is happening instead?**

If you run the demo, click into the textarea/tagify and click outside to trigger the blur/tagify#update event, you'll see that the tags are stripped in the console.

- **What error message are you getting?**

There's not an error message. It was actually quite a surprise!

Hopefully, there's a straightforward fix!

**Comment by atownley** [comment]
Unfortunately, this requires pre/post processing the HTML in order to facilitate the solution you mentioned. And it means you don't have the ability to easily round-trip things without a whole lot of extra effort.

Due to this issue and a few others, I've moved away from Tagify for mixed-mode content. I think it's great for tags, but I think there's a lot of stuff in mixed-mode it just doesn't handle well—this being one of them.

But it's all good. It's not really what it is for, and if it works for people in this use case, great. For me, I need something a bit different, and the change you made isn't doing to work for my usage scenario.

**Comment by yairEO** [comment]
Yeah I understand.. `mix-mode` is insanely difficult to develop, there are endless amount of browser bugs that I do not have time/motivation to address as I'm pretty thin on my motivation to continue programming after almost 3 decades.

When I started working on `mix-mode` in 2017 I thought how hard can this be. 
well, it's pretty much very hard. and it's not my fault, it's there are just so so many browser bugs and insane workarounds that has to be done around them.. and browser vendors won't fix a thing. frustrating. 

I did re-wrote the **whole** code in React 2 years ago to make a `mix-mode` version which works very well but have never released it.. it takes a lot of time to release a project because demo pages needs to be authored and README file and whatnot..
