### ISSUE TITLE
Hook "edit:updated" doesn't react to function replaceTag()

### ISSUE THREAD

**Issue by kirilpetrov36** [yairEO/tagify#1253]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation

- **I expect when I call function _ReplaceTag(i, t)_, the hook **"edit:updated"** is gonna react to this**

- **Function _ReplaceTag(i, t)_ works successfully but hook doesn't react to update, this hook reacts only when I change tag in EditMode**

- **I got no error messages**

**Comment by yairEO** [comment]
`edit:updated` callback is only invoked by a user action. 

`replaceTag` is called (internally) in all sorts of scenarios which are unrelated to editing a tag and therefore, if you the developer called that method, you already know a tag was updated and can directly call your callback, or you can call another internal high-level function `tagify.onEditTagDone(tagElm, tagData)` instead of `replaceTag` where `tagElm` points to the node you want to replace and `tagData` is the new data
