### ISSUE TITLE
Cross-site Scripting Vulnerability in @yaireo/tagify Package

### ISSUE THREAD

**Issue by TechnoRahmon** [yairEO/tagify#1292]
#### Description:
Our project has been flagged with a medium severity issue due to a Cross-site Scripting (XSS) vulnerability found in the `@yaireo/tagify` package. This vulnerability exists in all versions of the package, as improper sanitization within the `tagify.js` file allows for XSS attacks to occur.

#### Problem:
The XSS vulnerability poses a significant risk to our project's security, as it could potentially allow attackers to execute malicious scripts in the context of our web application, leading to various security threats such as session hijacking, data theft, and malware injection.

#### Impact:
If exploited, this vulnerability could compromise the integrity and confidentiality of user data, undermine the trustworthiness of our application, and result in potential legal and reputational repercussions.

#### Proposed Solution:
A fix has been implemented in the master branch of the `@yaireo/tagify` package; however, it has not yet been published. We kindly request the author or maintainers of the package to promptly publish the fix to mitigate the XSS vulnerability.

#### Steps to Reproduce:
The vulnerability can be demonstrated using the following proof of concept (PoC):
```
<img/src=x onerror=alert(document.domain)>
```

#### Additional Details:
Cross-site scripting (XSS) attacks occur when untrusted data is improperly sanitized and then executed within the context of a web application. This allows attackers to inject and execute arbitrary scripts, leading to various malicious activities.

#### Recommendation:
We strongly advise the author or maintainers of the `@yaireo/tagify` package to prioritize the publication of the fix to protect users and prevent potential security incidents.

#### References:
- [OWASP Cross-site Scripting (XSS)](https://owasp.org/www-community/attacks/xss/)
- [Snyk Security Advisory](https://snyk.io/vuln/SNYK-JS-YAIREOTAGIFY-1209224)

#### Impact:
This vulnerability has been identified as a medium severity issue by our project's Snyk scan, and addressing it promptly is crucial to maintaining the security and integrity of our application.

We appreciate your prompt attention to this matter and look forward to the timely release of the fix.

Sincerely,
Abdulrahman

**Comment by yairEO** [comment]
there is no vulnerability. closing.

**Comment by TechnoRahmon** [comment]
If you're unable to view the report and wish to avert your gaze, then it's genuinely worth contemplating switching from the Tagify library to another.

**Comment by yairEO** [comment]
sanitization should never be done in front-end, but only backend APIs.
I have been a believer in this for almost 20 years of designing highly complex web systems for large scale enterprises. 

Tagify is only a GUI for editing an completely ordinary `<input>` element's content. 
It's just a design overlay. 

You misunderstand how Tagify work if you think it has a scripting vulnerability, because in the end, Tagify is not, and never will be, a complete 100% solution for everything for a developer to drop and forget. 

A developer still needs to submit a form or data to a server, same as was done for decades, and this process is unrelated to Tagify. It's in the developer's hands to do whatever they want/need with the above mentioned `<input>` value, and if they are serious devs, they would already have sanitization in-place for every form and data submission to their backend -> database.
