### ISSUE TITLE
import Tags doesn't work in typescript

### ISSUE THREAD

**Issue by simkimsia** [yairEO/tagify#1364]
## Prerequisites

- [x] I am running the latest version (4.27.0)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Explanation

- **What is the expected behavior?**

I am expecting that 

```typescript
import Tags from "@yaireo/tagify/react"
```

in a typescript file to work perfectly

- **What is happening instead?**

i am getting this complaint

![image](https://github.com/user-attachments/assets/6e8fbe9e-e82d-4b26-8958-eaedffd0ef36)

and when i run `npm run build`

```
18:47:11 [build] Building static entrypoints...
node_modules/@yaireo/tagify/src/react.tagify.jsx (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
18:47:13 [vite] ✓ built in 1.35s
18:47:13 [build] ✓ Completed in 1.38s.

 building client (vite) 
node_modules/@yaireo/tagify/src/react.tagify.jsx (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
18:47:18 [vite] ✓ 1344 modules transformed.
```

- **What error message are you getting?**

see above

**Comment by blutorange** [comment]
I'm not affiliated with this project, but a few notes.

Regarding the missing type declarations, it was decided this project will not support TypeScript: https://github.com/yairEO/tagify/pull/531

TypeScript declarations are available via DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/yaireo__tagify

[There's a test on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yaireo__tagify/test/yaireo__tagify-react-tests.tsx) that uses the import `@yaireo/tagify/src/react.tagify` (you are using `@yaireo/tagify/react`) .

`@yaireo/tagify/src/react.tagify` corresponds to [the real path of the file within the package.](https://unpkg.com/@yaireo/tagify@4.27.0/src/react.tagify.jsx)

However, 4 months ago, [there was a commit in this repo](https://github.com/yairEO/tagify/commit/d12daa63875af9df1f315ba6dc748c75ffc9c3cf) that added the `exports` property to the `package.json`. This disallows any import from arbitrary paths in the package; imports must now use `@yaireo/tagify/react`. (Since that is a breaking change, the major version should have been incremented).

Anyways, it seems the typings on DefinitelyTyped need to be updated, so you should probably open an issue there.

**Comment by simkimsia** [comment]
> I'm not affiliated with this project, but a few notes.
> 
> 
> 
> Regarding the missing type declarations, it was decided this project will not support TypeScript: https://github.com/yairEO/tagify/pull/531
> 
> 
> 
> TypeScript declarations are available via DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/yaireo__tagify
> 
> 
> 
> [There's a test on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yaireo__tagify/test/yaireo__tagify-react-tests.tsx) that uses the import `@yaireo/tagify/src/react.tagify` (you are using `@yaireo/tagify/react`) .
> 
> 
> 
> `@yaireo/tagify/src/react.tagify` corresponds to [the real path of the file within the package.](https://unpkg.com/@yaireo/tagify@4.27.0/src/react.tagify.jsx)
> 
> 
> 
> However, 4 months ago, [there was a commit in this repo](https://github.com/yairEO/tagify/commit/d12daa63875af9df1f315ba6dc748c75ffc9c3cf) that added the `exports` property to the `package.json`. This disallows any import from arbitrary paths in the package; imports must now use `@yaireo/tagify/react`. (Since that is a breaking change, the major version should have been incremented).
> 
> 
> 
> Anyways, it seems the typings on DefinitelyTyped need to be updated, so you should probably open an issue there.

Oh thank you for the clear comments

Indeed I wasn't aware of the decision not to support typescript 

Which I can totally accept

One question because I'm not very familiar with typescript and npm, if the DefinitelyTyped package is slow to fix, is there a way for me to fork DefinitelyTyped and then make my own npm package?

I'm more familiar with python ecosystem and sometimes when the dependency is slow to update I can still use pip and point to a fork from a GitHub repository 

I wonder if there's a similar way to do this with npm

**Comment by blutorange** [comment]
> One question because I'm not very familiar with typescript and npm, if the DefinitelyTyped package is slow to fix, is there a way for me to fork DefinitelyTyped and then make my own npm package?

You can always just make a PR : ) Then it's pretty quick, the release process is automated.

**Comment by simkimsia** [comment]
> > One question because I'm not very familiar with typescript and npm, if the DefinitelyTyped package is slow to fix, is there a way for me to fork DefinitelyTyped and then make my own npm package?
> 
> 
> 
> You can always just make a PR : ) Then it's pretty quick, their release process is automated.

I just realised you're the same Blutorange I tagged in yaireo__tagify 

Ok 
I'll give this a try tomorrow

**Comment by simkimsia** [comment]
Since this isn't strictly a tagify issue, as it doesn't support typescript, i will close this. 

What I did was, i downgraded to v4.24.0 for now.
