### ISSUE TITLE
t.forEach is not a function

### ISSUE THREAD

**Issue by YeZawPaing** [yairEO/tagify#1393]
## Prerequisites

- [x] I am running the latest version
- [x] I'm using this cdn <script src="https://unpkg.com/@yaireo/tagify"></script>

### 💥 Demo Page
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <input type="text" name="email" class="tagify">
</body>
<script src="https://unpkg.com/@yaireo/tagify"></script>
<script>
    var input = document.querySelector('input[name=email]');
    new Tagify(input);
</script>

</html>
```
### Explanation

- **What is the expected behavior?**

- I expected it to work just like the examples, but when I used it, the following errors appeared

tagify:28 Uncaught TypeError: t.forEach is not a function
    at Q.addTags (tagify:28:67646)
    at Q.loadOriginalValues (tagify:28:53518)
    at new Q (tagify:28:48502)
    at index.html:16:5

**Comment by CasualJon** [comment]
Found this as well when using vanilla's latest from jsdelivr. 
Downloading source from release v4.31.3 and loading that locally does not encounter the issue, so it's happening only in v4.31.4 - at least for me.

Looking at the sources tab to inspect the error, I'm finding the following - I'll admit I don't know this is the cause of, caused by, or neither for the t.forEach is not a function error...
![Screenshot 2024-10-24 at 4 38 26 PM](https://github.com/user-attachments/assets/ebff9238-86ba-4067-aaee-672ab6b45a42)

**Comment by BriCusack** [comment]
I just got this morning 4 hours out from a production build deployment 🤣

**Comment by preshndams** [comment]
I'm currently facing same issue, please any idea on how to fix?

**Comment by Maremic** [comment]
![image](https://github.com/user-attachments/assets/92941f76-6a9e-46d5-bd6d-17730d0f2c0c)
the same issue

**Comment by YeZawPaing** [comment]
I think it's happening on latest version which is 4.31.4. If you add previous version to the cdn, it will fix the issue temporarily like this.
<script src="https://unpkg.com/@yaireo/tagify@4.31.3"></script>

**Comment by BriCusack** [comment]
> I think it's happening on latest version which is 4.31.4. If you add previous version to the cdn, it will fix the issue temporarily like this.
> 
> <script src="https://unpkg.com/@yaireo/tagify@4.31.3"></script>

Yes, was an oversight during code review. Always lock your versions and or use a package manager with set periodic update reviews.
