### ISSUE TITLE
jQuery version split whitelist values by space.

### ISSUE THREAD

**Issue by cf-git** [yairEO/tagify#147]
Hello, thank you for beautiful work!

I get a problem with jquery version of you script.
When in white list value has space, chosen value is divided into a few words.
I mean from value like 
`{"id":1,"value":"some string"}, ...`
on choice to input script pust 2 word 'some', 'string'

Then when i use a base version is ok.
Is not a big problem, however it can call other problems in scripts.
So, thank you and good luck

**Comment by yairEO** [comment]
this cannot happen since the jQuery version is identical to the base version, it's only a wrapper. I've just checked this on the demo page and I cannot reproduce this.

I've set the `whitelist` of the jQuery _Tagify_  to have `{"id":1,"value":"some string"}` and typed "som.." and chose that value from the dropdown suggestion list and everything worked as expected.

**Comment by yairEO** [comment]
Anyway, you really do not need to use the jQuery version since the vanilla one can be integrated just as easily!
