### ISSUE TITLE
Autocomplete related issues/fixes

### ISSUE THREAD

**Issue by ElvenDev** [yairEO/tagify#16]
Currently, I have an issue where I have around 330 whitelisted items. Issue what it has is when it loads all together at once when I started typing, the browser becomes laggy. I don't have that shit computer, so I assume the most user would have the same issue. So, there is 2 recommendation, to add to autocomplete (or at least add a setting option for possibly support it!)

1) Reduce the length of displaying all options and add a search bar to it. The search bar part should be an option not recommended, as if there aren't that many searchable options, it might become more pain, but having that option when whitelist is bigger, will help a lot! Below is example picture what another datatable plugin is using (Not tag support tho, ;))
![image](https://cloud.githubusercontent.com/assets/20682644/24395334/ffd1a2ba-13a7-11e7-8d68-7b34d7041e90.png)
2) Add option from when it will start autocompleting. Usually, it is the third character. This should be also an option, as if there are few characters, having it from first adds to the user experience. If you have however 330 whitelisted options, loading on the first character can be discouraging.

Also side note: That arrow what you disappeared actually destroyed a bit friendliness. I usually try to think that all clients are actual dumb-users and if they see box, but no way to open the option list, it can be confusing to them. It is not that huge of an issue to me, as I simply reversed the CSS file commit, but just a small thought I had.

Also, is it possible to donate for this project? I feel like you have done quite a lot, especially recently.

**Comment by yairEO** [comment]
But it already decreases the number of suggestions *as you type*, so I don't understand how (1) will help much. it will also require another plugin which will make the code much much bigger..I'm trying to keep it as small (filesize) and performant as possible.

Your second suggestion seems the best because 2-3 minimum characters before showing the datalist will definitely decrease the number of suggestions shown. 

I can't believe it actually makes your browser slow.. 330 (datalist options) is a very small number for a browser. Facebook has thousands of HTML elements and it's pretty smooth.
I didn't try so many myself but I will try today to load an English dictionary as my suggestions :) see how it behaves. 

Regarding that arrow, it was only on Chrome and since I work with FF and I wanted chrome to look like FF I removed that arrow. the suggestions are shown anyway if you click on the input inside the Tagify, and users have to click on it anyway in order to type, so they will see the suggestions list no matter what, don't you agree?

Yes donations are welcome :) you can send it to my PayPal account:
vsync.design@gmail.com

I feel obligated to to open source community and try to work on my projects at night, after work, as much as I can, and I am happy people like you open issues for me. it means there is a demand for my work and it actually help others. I have another new project which I'm working on and will upload to Github next week.

**Comment by ElvenDev** [comment]
Awesome!

The problem isn't that 330 is a lot of data. The problem is trying to show them all at once. Also, I just found out that since I pretty much only use chrome, that particular issue is only there.

![image](https://cloud.githubusercontent.com/assets/20682644/24396522/2dff3e5a-13ac-11e7-9b05-15a827082886.png)

So, just adding support to reduce the box (setting auto length, at least at chrome) also helps, since the user will have to type anyway. So I agree that maybe search box is unnecessary.

I personally disagree with an arrow. For me, I had to double click for it to show. While for me, developer and basically computer fanatic, it is not a problem, it might become an issue for those who are not (I have had to work with some for a while, so I have a bit experience). So, adding dumb-user support (arrow), just to show that "If you click here, you can open all suggestion list!", will help a lot and make the user experience better. Sometimes if user see the input, they do not click immediately as they do not know what it is. Arrow however screams "CLICK HERE!"!

**Comment by yairEO** [comment]
Chrome has a known bug regarding that:

https://bugs.chromium.org/p/chromium/issues/detail?id=375637

it would help if you "star" the bug so they will give it higher priority and it might be fixed soon.
Firefox shows a scrollbar correctly so the list is never too long, but I will implement your second idea so the list will not be shown until a minimum number of characters were applied

**Comment by ElvenDev** [comment]
Apparently, ios safari also shows full list too.

I personally think it is a wrong approach to "Wait for official bug fix somewhere", what might be fixed in 10 years. Meanwhile, our consumers must use bugged version. But I guess I can try to apply a third-party myself for now :).

Thank you for the minimum characters idea. Make sure to add an option to enable/disable it or set minimum character amount, so people can set it to show straight away if data amount is small.

Also, I still recommend adding arrow into all 3 browsers.

Thank you!

**Comment by yairEO** [comment]
yes Safari is webkit and Chrome is also webkit, they use the same browser engine which inherits the same bugs. they wrote in the bug that it will be fixed very soon, probably matter of weeks I hope. I don't know how to add the arrow to FF, because that is something which is specific for webkit browsers, but it's easy to return that arrow, you just need to edit the CSS and bring it back. remove the line where I hide it.

**Comment by ElvenDev** [comment]
Yes, already done that :).

**Comment by ElvenDev** [comment]
Thank you!
