### ISSUE TITLE
Incorrect interaction between enabled and maxItems for dropdown

### ISSUE THREAD

**Issue by afonso-brito-carvalho** [yairEO/tagify#217]
If you initialize a tagify instance with enabled: 0 (showing dropdown on click, without the user typing), and attempt to limit the dropdown with maxItems, the first initial dropdown will not be limited.

The maxItems option only appears to be used when the user types, and not on the first display of the dropdown.

**Comment by yairEO** [comment]
Can you elaborate?

**Comment by afonso-brito-carvalho** [comment]
Sorry, pressed enter too quickly!

**Comment by yairEO** [comment]
That is indeed a nice bug, I will solve it asap.

**Comment by yairEO** [comment]
Now that I think of it, I remember that this is the correct behavior that I decided to have.

Showing the whole list by applying the setting: `dropdown:{ enabled:0 }` means the dropdown is not filtered, therefor it makes no sense to limit the items shown, because why show some and not others? that is an unfair treatment. 

But, if the dropdown setting did have the `enabled` property with any integer value above `0` then the list would at least be filtered by some criteria and then, it makes more sense to allow limiting the results list.

![image](https://user-images.githubusercontent.com/845031/55910923-3b7b7e00-5be8-11e9-9f2f-bdc0f31f5389.png)

As you can see, the `suggestedListItems` is not being filtered when the value is empty (`enabled:0`).

That said, I am willing to make the change to allow that and see if anyone would complain. Will make it now so hold on.

**Comment by afonso-brito-carvalho** [comment]
To me, it makes sense as a consistency issue, since only limiting the dropdown in some cases catches people by surprise. In my usecase, I have about 20-30 possible items, and I was having users see a huge dropdown that shrank down to 2-3 items when they started typing.

Thank you for the change!
