### ISSUE TITLE
Allow Catch-All for Mix Mode

### ISSUE THREAD

**Issue by nahtnam** [yairEO/tagify#242]
Hello,

I have an interesting suggestion for mix mode. The use case I am going for is allowing people to add hashtags to their messages. If the hash tag exists already, that's great, it will show up in the autocomplete. The problem is if it doesnt then mix mode will not detect it since it's in the whitelist. I was wondering if it was possible to add either the option to:

1. Add a entry that says "make your own hastag"
2. Allow anything that starts with the hastag (or regex) a tag automatically, but if the user presses backspace then it goes from being a tag to text only.

What do you think? I know todoist does option two (I can provide a video example if it doesnt make sense)

**Comment by yairEO** [comment]
Regarding (1), yes, it has been in the roadmap to allow creating mix-mode tags which aren't included in the whitelist. I will try to work on that this week.

Regarding (2), I think this should be a setting, if backspace removes the whole tag or just un-tag the tag, making it text again, which is much more tricky to code, because of caret position issues.

**Comment by nahtnam** [comment]
Yeah I understand 2 is going to be very complex, so 1 seems like a good middleground! Thank you for this project, I can't even begin to understand how to build this myself

**Comment by yairEO** [comment]
For now you can set the `backspace` setting to *"edit"* which will not remove the tag when pressing the <kbd>backspace</kbd> key but rather enter into "edit mode".

Transforming the tag to a textNode will be a one-way destructive process, because if there was any space in the tag, after it has been transformed into a textNode, I can no longer convert it to a tag, because of the space. It's a technical problem to differentiate what is a tag and what not when a space is present.

**Comment by yairEO** [comment]
Creating new tags has been implemented, closing.
