### ISSUE TITLE
Sort Tags

### ISSUE THREAD

**Issue by shakeeb-mts** [yairEO/tagify#260]
Hi,

I was wondering if you have plan for making the tags sortable.

Thanks

**Comment by yairEO** [comment]
You can sort them yourself. 

What **exactly** do you need? 
Please explain every step of the desired UI

**Comment by shakeeb-mts** [comment]
If you check this plugin https://goodies.pixabay.com/jquery/tag-editor/demo.html

It has two jquery ui widget integrated..
- jQuery UI sortable 
- jQuery UI autocomplete

Well autocomplete thing is we have inform of whitelist... but we can't sort the tags order.

**Comment by yairEO** [comment]
I have [another script](https://github.com/yairEO/dragsort) I wrote which can do that and I can write an example code how to combine them both

**Comment by Jiramew** [comment]
@yairEO Will you give an example on combining dragsort and tagify, thanks so much~

**Comment by yairEO** [comment]
Hi, I was on vacation. I don't have a working example, I would need to make one, I guess it's not so trivial and would require some experimentation. Maybe on the weekend.

**Comment by josefglatz** [comment]
> I have [another script](https://github.com/yairEO/dragsort) I wrote which can do that and I can write an example code how to combine them both

That would be really nice!

**Comment by yairEO** [comment]
I will work on it soon

**Comment by Daijobou** [comment]
Hello YairEO, I would like this function too. Currently I use select2 for tags input with jquery-ui widget sortable for sorting tags.

**Comment by yairEO** [comment]
@Daijobou - I will try to make time to construct a demo

**Comment by MyThemeShop** [comment]
Hello @yairEO 

Looking forward to it. It would be really helpful for us in our projects.

**Comment by gpetrov** [comment]
Well I hope this gets implemented soon @yairEO 

Something like this should be pretty easy to do:  https://jsfiddle.net/jkLhfzr8/

**Comment by yairEO** [comment]
If you think this is easy then you should know such things take days-weeks to make. I will get to it, it's not high in demand since most developers don't need sortable tags, it's a not-so-common UI feature.

**Comment by yairEO** [comment]
I will get to it, but if you think drag & drop is easy, you are very much wrong. is it very hard to get it right. A ton of calculations needs to be made on-the-fly while also maintaining a high code-standard/low-footprint and fast performance. 

This is a highly complex feature which I need to invest many days on, probably over a week. As I said already above, I've already created a few years ago a drag & drop script, which works, but I'm unhappy with it and it needs complete re-write.

I cannot integrate it directly into *Tagify* because it will bloat the code, so it would have to act as a *plugin* to *Tagify* because this feature is quite uncommon in UIs.

**Comment by yairEO** [comment]
Added a demo how to combine [dragsort](https://github.com/yairEO/dragsort) with *Tagify*:

https://github.com/yairEO/tagify#drag--sort

**Comment by josefglatz** [comment]
So many thanks!!!!!!!!!
