### ISSUE TITLE
DOM.originalInput not updated when remove a tag by click cross button in mix mode

### ISSUE THREAD

**Issue by batcat75** [yairEO/tagify#266]
Hello,

I'm using tagify in mix mode and I need to get the value of the textarea.

The value of textarea is just like this
val() = "[[Tag1]] [[Tag2]]"

After that, I want to remove the "Tag2" by click the cross button.
The display will removes it but the value in textarea is still the same.

I guess in the function "**removeTag()**" it call the "**animation()**" function.
So, The target node will remove in 400 ms later but "**update()**" is already call.

```
removeTag: function removeTag() {
   ...

    if (tranDuration && tranDuration > 10) animation();else removeNode();

    if (!silent) {
      tagData = this.value.splice(tagIdx, 1)[0]; // remove the tag from the data object

      this.update(); // update the original input with the current value

      ...
    }

    function animation() {
      tagElm.style.width = parseFloat(window.getComputedStyle(tagElm).width) + 'px';
      document.body.clientTop; // force repaint for the width to take affect before the "hide" class below

      tagElm.classList.add('tagify--hide'); // manual timeout (hack, since transitionend cannot be used because of hover)

      setTimeout(removeNode, 400);
    }
}
```

**Comment by yairEO** [comment]
Thanks, I'll take a look as soon as possible

**Comment by batcat75** [comment]
Thank you for your support 
Best regards

**Comment by suzumejakku** [comment]
Hi @yairEO ,
Not sure whether the bug came back or if I am doing anything wrong, but I have the exact same issue with v4.12.0. I created a simplified sandbox here, based on your original Vue 3 example:

https://codesandbox.io/s/tagify-tags-component-vue-example-forked-eyw3iq?file=/src/App.vue:1617-1634

See the console.logs. After having added a tag, if you remove it, a call to `event.detail.tagify.DOM.originalInput.value` still shows the value of the removed tag. If you add text or another tag, the next call to `event.detail.tagify.DOM.originalInput.value` shows a correct content.
