### ISSUE TITLE
Send request after press Enter

### ISSUE THREAD

**Issue by shaste** [yairEO/tagify#278]
It is possible to send request with tagify values after pressing Enter?

For example, I entered two tags from autosuggest [tag] [tag 2]. Then i would press enter and submit form. I had button for this but i want to do it with keydown event too.

 How can i do that?

**Comment by yairEO** [comment]
You can ask on StackOverflow because this is not related to Tagify and I sadly have no time to help at the moment. 

Custom keyboard events are handled by you, the developer, in your code. if you want something to happen when some key is pressed, then google how to do it. You also need to take into account in what context are you pressing <kbd>Enter</kdb> because it's important to understand which element has the current focus while pressing the enter key. You also need to check if something has been typed inside the Tagify Input element, and if so, ignore the key press until the tag was actually added.

I feel from your question that you will struggle with making all this work?

**Comment by shaste** [comment]
oh sorry, I thought Tagify has that keydown method already. I thought I missed it and asked a question. 

Thank you for direction and explanation, i will try this.

**Comment by scflode** [comment]
Sorry to necro post here. But doesn't tagify intercept "enter" and add a `e.preventDefault`? 
https://github.com/yairEO/tagify/blob/master/src/tagify.js#L666

This breaks form submission on enter. It's not hard to solve but you need to know that tagify is modifying the default form behavior. Maybe it can be mentioned in the readme?

**Comment by scflode** [comment]
Sorry. Nvm. I was mistaken. It's a different element.

**Comment by yairEO** [comment]
You shouldn't think about the events as "enter" was pressed, because some people use the mouse or touch devices and even automatic readers for the blind. If you want an action to happen at a specific time, then use the [build-in Tagify events](https://github.com/yairEO/tagify#events) (such as "add" event)

**Comment by scflode** [comment]
Yes, I was confused as I am using it as a search filter field and thought on Enter the for should be submitted. But this does not work easily as Enter selects the tag. There is no chance to know (at least I didn't find anything) what context the Enter was done in. I can overload the default handler but then it will submit always.

Thanks for the quick answer and the clarification.
