### ISSUE TITLE
conflict "RENDER SUGGESTIONS LIST MANUALLY" Property with "TEXTAREA"

### ISSUE THREAD

**Issue by amirhoseinBK** [yairEO/tagify#286]
you can see this conflict in your page https://yaireo.github.io/tagify/
when I add Goodfellas in second input in fifth input A#.NET will automatically add
I do not know why this happen but this do not happen reverse

**Comment by yairEO** [comment]
I see it. hmm

**Comment by yairEO** [comment]
Ok I know why this happens. 

It's because originally I've made it so all the instances of `Tagify` share the same dropdown suggestions menu container, for performance reasons, because I based this on the assumption there could *never be more than 1* rendered dropdown at the same time, which isn't the case anymore with manual rendering. I will fix it.
