### ISSUE TITLE
ES6 modules

### ISSUE THREAD

**Issue by cowwoc** [yairEO/tagify#305]
This is more of a question than anything else... Would switching to ES6 modules improve tree-shaking on your library? Meaning, would it improve the chances that webpack, rollup, etc would strip away unused features?

Looking at https://bundlephobia.com/result?p=@yaireo/tagify@2.28.4 vs say https://bundlephobia.com/result?p=d3@5.12.0 you can see the latter is tree-shakable which means unused code will be removed. It would be nice to get the same from this library.

I also don't think it would take much to convert to ES6 in your case.

You can use rollup.js to provide multiple outputs: ES6 and IIFE (the latter being what you provide now).

**Comment by yairEO** [comment]
I was considering it for that reason in the past, but since Tagify is so lightweight, only ~8kb GZIP all this effort will barely save `1kb`, so I chose to stick to [`UMD`](https://www.npmjs.com/package/gulp-umd) build.

Do you think it's worth it?

**Comment by cowwoc** [comment]
@yairEO The be honest, it's probably not going to save a lot of space because you only really have 1-2 modules. That said, I suggest moving towards ES6 classes, modules in order to improve readability. The newer syntax is more restrictive which has the effect of making it more concise.

**Comment by yairEO** [comment]
what do you consider a module in Tagify? 
*Tagify* is single-function which is meant to be instantiated. 

Personally I dislike Classes because of the syntax and also because they aren't real Classes but a way to make people coming from other languages feel more "at home".

My first and only language is javascript, and I like how dynamic it is, and I like writing using prototypes because I'm used to it for many years now, and it has no disadvantages over Classes. [Here's Some article I've found](https://medium.com/javascript-scene/master-the-javascript-interview-what-s-the-difference-between-class-prototypal-inheritance-e4cd0a7562e9).

Another discussion on [StackOverflow](https://stackoverflow.com/a/816075/104380)

Anyway, I compose Tagify's code to be tight and efficient, So for me the important things are:

1. keeping the codebase small (working DRY as much as possible)
2. Try not to use fancy ES6 syntax which will be transpiled into bloated code, so this means I have to code it to avoid transpilation as much as possible.
3. keep the performance highly efficient

**Comment by cowwoc** [comment]
@yairEO Sounds good. Thanks for the consideration.
