### ISSUE TITLE
Not working in bootstrap popover

### ISSUE THREAD

**Issue by codertimu** [yairEO/tagify#319]
Hi,

tagify does not work when used in a bootstrap popover.

example HTML:

```
<div class="container">
    <a tabindex="0" href="#" id="tglr" class="popover-toggle" title="Popover Header">Toggle popover</a>
    <div id="customdiv" style="display: none">
        <button class="btn-info">Button</button>
        <input name="basic2" value="tag1, tag2" />
    </div>
</div>
```

and script:

```
<script>
    $(document).ready(function(){
        // var input = document.querySelector('input[name=basic]');
        // new Tagify(input);

        $('#tglr').popover({
            // container: 'body',
            html : true, 
            sanitize: false,
            content: function() {
                return $('#customdiv').html();
            } 
        });
        
        $('#tglr').on('shown.bs.popover', function () {
            var input2 = document.querySelector('input[name=basic2]');
            new Tagify(input2);
        });    
    });
</script>
```

I also had to initialize Tagify in shown.bs.popover event of popover. 
Problems:
The input does not turn onto a tagify on first opening.
~~It turns into tagify on the subsequent opening of popover but each time it creates a new input.~~
^I understand this is because I initialize it every time popover shown. But where should I initialize it to be able to work in popover?
Yet removing/clicking/typing does not work.

I also tried:
`.tagify__dropdown {z-index: 11111! important; }
` but didnt help.

**Comment by yairEO** [comment]
I will check in the upcoming days, thanks for reporting

**Comment by yairEO** [comment]
Sorry but without a working demo I cannot figure out what is best in your situation.

**Comment by codertimu** [comment]
Here it is:
https://jsbin.com/cilesexiwe/edit?html,css,js,output

**Comment by coding-tech-guy** [comment]
Hi @codertimu 

When you fire tagify within the `shown.bs.popover` event, you are attempting to apply this to input2 which is selector `input[name=basic2]`. The issue is the selector `input[name=basic2]` already exists on the DOM at load, as the popover is only a copy of the html from "#customdiv". This means when tagify fires, its applying it to the hidden input2 and not that of the popover.

**Solution:**

Outside of the popover, you need to create a variable to hold the html contents of "#customdiv" and then remove "#customdiv":

`var content = $('#customdiv').html();
$('#customdiv').remove();`

You can then apply this as the content of the popover:

`            content: function() {
                return content;
            } `

And now when tagify fires, it will be against the input2 selector within the popover.

**Comment by codertimu** [comment]
It worked, thank you very much.
