### ISSUE TITLE
Auto-complete behavior

### ISSUE THREAD

**Issue by pesseyjulien** [yairEO/tagify#321]
Hi,

Thanks again for sharing this repo.

Quick question, any idea how to make whitelist auto-complete orderless ?

For example, I have {"value":"Ligue Europa","data-id":"6,524"} as one value of my whitelist, but it does not appear if I start taping with 'europ', only if I start with 'ligue'. 

Any idea how to fix/change this ?

Thanks, 
Julien

**Comment by aquaductape** [comment]
Could you share you're tagify settings? Maybe you set `dropDown.fuzzySearch` to false

**Comment by pesseyjulien** [comment]
var tagifyCompetition = $('[id=competition]').tagify({
            enforeWhitelist: true,
            whitelist: {{ligues|json_encode|raw}},
            mapValueToProp : "data-id"
        });

**Comment by yairEO** [comment]
how can a whitelist item be auto-completed not from the beginning? 

For `Ligue Europa`, if you start typing "eur" then suggesting the rest will not be heppful: "europa". it will miss the first word "Ligue ".

The way it behaves now is intentional

**Comment by pesseyjulien** [comment]
alright, thanks for your answer. No workaround then ?

**Comment by aquaductape** [comment]
You could fork this repo and use a fuzzy-search library called fuse.js instead of the provided one. Like this library, fuse.js is lightweight and doesn't use any dependencies. Go to the `dist/tagify.js` around line 1510 replace the for loop block with fuse.js configuration and function. You could [look at mine for reference](https://github.com/aquaductape/tagify/tree/master). If you want to use my repo `npm install https://github.com/aquaductape/tagify.git#fuzzy_with_fusejs`

**Comment by yairEO** [comment]
@aquaductape - no need for that **at all**.

you can clone the repo and simple change 1 line:

https://github.com/yairEO/tagify/blob/master/src/tagify.js#L1294

since I do not understand the logic in doing so, I cannot make any changes to Tagify to allow this. If anyone wants to change my mind, please explain to me, in details, a scenario where such behavior would be a good UX.
