### ISSUE TITLE
Passing id through events (accessing the orginal element in native js)

### ISSUE THREAD

**Issue by tomelsj** [yairEO/tagify#346]
Hello I have run into a problem where there seem to be no way to know which DOM input the event is fired for. This assumes that there are several tagify instances running for different elements. The  ev.originalTarget, ev.srcElement and ev.target returns an empty "#text" reference.

Here is an example: https://jsbin.com/peburepune/edit?html,js,output

Workaround: It seems you can get the input element by ev.explicitOriginalTarget.parentNode.parentNode.querySelector("input")

**Comment by yairEO** [comment]
Here are three methods on how to access the input:
https://jsbin.com/hatozekexe/1/edit?html,js,output

don't use `explicitOriginalTarget`, it's not a good solution. You already have a reference to the input elements, since you used it when you "tagified" them, so you can simply pass that reference to the callback function, as shown in the examples I've prepared for you above
