### ISSUE TITLE
Accessibility: [aria-*] attributes do not match their roles

### ISSUE THREAD

**Issue by Monokai** [yairEO/tagify#393]
I'm running Chrome Lighthouse Audits on your code, and it complains about aria roles and attributes. You can also see these messages in Chrome > Dev Console > Audits if you test this page: https://yaireo.github.io/tagify/

The code still works fine, but it would be nice if it 100% passes the accessibility audits.

**Comment by yairEO** [comment]
I will look into it, thanks

**Comment by yairEO** [comment]
I am not an expert of web accessibility markup, it's all a deep deep mess, but I have made a few changes which might alleviate the score. will push a new version now

**Comment by ilicmarko** [comment]
This is not improved and in my opinion, shouldn't be advertised as a11y supported. This will create problems with any accessibility tool and is a major turn off. If the WAI-ARIA isn't implemented by the spec why implement it.

Don't get me wrong Tagify is awesome and it does what it was created for but why add aria support which is wrong and will complain?

The problem here is the use of "custom" role attributes. Role attribute has predefined values that should be used and certain constrained per role.

This is part of [WAI-ARIA 1.1 - Section 5.4 Definition of Roles](https://www.w3.org/TR/wai-aria-1.1/#role_definitions).

What the actual role here should be is a `combobox` ([spec](https://www.w3.org/TR/wai-aria-1.1/#combobox)). But the problem with this is the current structure doesn't support this as the `listbox` spawns on click.

Please try to understand my side, working as a performance consultant, and having to explain this to the client is... well... irresponsible.

![image](https://user-images.githubusercontent.com/2827249/80238303-7e2abf80-865e-11ea-912c-3c8d5ded5b5c.png)

I am working on overriding this or making a custom version. I will edit this post if I am able to improve this.

**Comment by yairEO** [comment]
I totally agree and understand you, I too struggled greatly accessibility support, there was so much conflicting & confusing information on the web, and I had spent so many hours trying to sort the mess and apply it well to Tagify, but accept my failure and greatly appreciate your help with fix all those accessibility attributes.

Are you an accessibility specialist (in the sense of HTML markup)?

**Comment by ilicmarko** [comment]
Wouldn't call my self a specialist, more like an idiot who likes to read the specs. 😄
I would like to make the web a more performance and accessible platform, trust me people are not a fan of these ideas. You? You really tried!!! 🙌 

I agree with you, and I think there is a great challenge to designing something like this because either you are going to sit down and read the specs, and trust me they are not an easy pill to swallow as they are written in a specific way or you will try to lookup it up in articles (medium)... The problem with this there are multiple ways to do something and there is a lot of conflicting information. I fully support you.

---

Yup, from Serbia. Really nice to hear that, not many people know about Serbia. Those that do say we are really friendly and welcoming to visitors.
