### ISSUE TITLE
Events before tags are effectively added or removed from tag list

### ISSUE THREAD

**Issue by fredgo321** [yairEO/tagify#418]
This is a great plugin that i intend to use.
Yet i would like to add or remove tags in the input list only after some server side operations success (for instance custom validation / backend inserts or delete success)

I was looking for some beforeTagAdded & beforeTagRemoved events or a way to perform that with the current settings.

Thanks by advance for your help !

**Comment by yairEO** [comment]
Not at the moment, but I think in terms of UX, it's common practice to first add or remove something and then, if there was a server error, return the state to the way it was before. The logic here is that server fault is uncommon and most of the time users will benefit from instant results to their actions, instead of waiting for things to happen on the screen.

If you added a tag which had some server issue being added, it's easy to remove it because you have DOM *node* reference in the event listener.

If you removed a tag and encountered some error, then you can add it back, because again you will have a reference to the DOM node (even though it was detached) and you also have the `index` (`e.detail.index`), so you can add it back.

The only problem now is keeping Tagify's internal state in sync with your manual DOM changes. if you are using React or any other framework, then you should not directly work with the DOM, *BUT* you can work with that framework's state, so you can return things the way they were fairly easily.

If you do however use Tagify in vanila-js, then you should make sure you update `tagify.value` array with the correct state after your DOM remediations.

**Comment by ShafiqueMalik** [comment]
I am using this settings  =>
 tagify({
            addTagOnBlur: false,
            editTags: false,
            mode: "mix",
            pattern: "",
            backspace: false
        })
Backspace key still removing tags. Is there any to stop deleting tags on backspace while we are in mix mode?

**Comment by yairEO** [comment]
I've curious, why don't you want backspace allowed?
How can users change their minds after writing a tag?

I've never ever considered someone would want such a thing, so I ignore the `backspace` setting on *mix-mode* 

I can change it so it won't be ignored but you'll need to wait for the next version of Tagify (within a few days)

**Comment by yairEO** [comment]
I understand and will work on it

**Comment by yairEO** [comment]
See (new) [hooks section](https://github.com/yairEO/tagify#hooks) in README
