### ISSUE TITLE
Outside Placement Issue

### ISSUE THREAD

**Issue by mete89** [yairEO/tagify#483]
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Demo Page
https://jsbin.com/dadefenure/1/edit?html,css,js,output

### Explanation

- **What is the expected behavior?**
When using outside feature, If I type something and then click on a link/submit button below (without pressing enter or clicking anywhere on page), I expect tagify puts the value outside (because it triggers a blur event) and then click event must continue.

- **What is happening instead?**
Since I'm using outside feature, in the first item addition, placement of the items below tagify changes toward downside. Click events on links or buttons don't occur at all. 

- **What error message are you getting?**
No error at all. The actual click event is gone away.

**Comment by yairEO** [comment]
It's only because the first time there's no tag so when you add the **first** tag the "link" is pushed down, because the `mousedown` event on the link caused a `blur` event on Tagify, which added a new tag, and that tag pushed the link down, so by the time your finger is firing a full "click" event (with `mouseup`) the link is no longer where it was.

It is how browsers decide to behave, but you will notice that if you already had a tag there and simply added another, the link will work.

###What does this tell you?
That you should make changes so the link will not move

###What changes?
put the link somewhere else, or make a fixed height for the tags area.

**Comment by mete89** [comment]
Hi @yairEO,

Thanks for the explanation. In my case, I request email list from users so I need to make it empty at first. Additionally, I can't put link somewhere else because its actually a submit button in a form. You can think it as the comment button on this github page. 

Fixed height is only logical solution for me. Is there any easy implementation for this solution that you can suggest? 

Thanks
