### ISSUE TITLE
add required option

### ISSUE THREAD

**Issue by kerolloz** [yairEO/tagify#488]
for example if I am using Tagify inside a form and I would like the tags input to be required.

**Comment by yairEO** [comment]
You can add `required` attribute to the original input element and it would work, but you would also need to explain the user the Tagify component is required (since the original input is hidden).

How does your form submit process work? do you manually validate the form fields?

**Comment by kerolloz** [comment]
For example if I have a very simple form that takes username and his interests(Tagify input). I know if I set the interests input to be required. The user won't be able to submit the form but he won't get the normal `this field is required` message (the input field itself is hidden). Not very good UX, you know. So know I have to write some logic for the required input and display the errors manually. Too much headache to implement a very simple _required_ input. Please let me know what do you think?

**Comment by yairEO** [comment]
Every developer should do this manually because every developer has different design requirements for handling `required` field. 

Do you suggest I decide for everyone how Tagify should look like when it's required? What if I choose to have a bright pink border and a flashing alert message? would you like that?
