### ISSUE TITLE
support reordering

### ISSUE THREAD

**Issue by zenlunatics** [yairEO/tagify#511]
thanks for the excellent code. I may be the only one, but the one feature I would really like is the ability to reorder the tags by dragging and dropping.

**Comment by yairEO** [comment]
Yes it's already discussed ain 3260 so i'm closing this as duplicate.

Currently I need to develop a drag & drop tiny library which can then be made to workout together with Tagify, and to be able to build this drag & drop lib I need a lot of free time which I currently don't have because of a full-time job
