### ISSUE TITLE
Don't include css in React wrapper?

### ISSUE THREAD

**Issue by danqing** [yairEO/tagify#528]
Thank you for this great library!

I'm trying to use it with next.js, a popular SSR-friendly React framework. However, I get the following error:

```
./node_modules/@yaireo/tagify/dist/tagify.css
Global CSS cannot be imported from within node_modules.
```

This is because the React wrapper imports the CSS file. Is there any chance we can import the CSS ourselves and not bundling it to the React JS?

Thanks!

**Comment by yairEO** [comment]
hmm this is a valid request. Can't you bypass this somehow?
If I remove the CSS file now from the React wrapper, it will definitely break the code for developers who might update Tagify version after the change and will suddenly discover they have no CSS.

I can release a statement for the new version with the breaking changes documented, however I would like first to know if there something that can be done by you to bypass the problem.

I see a lot of complains about this bizzare `next.js` choice of not supporting which tells me this is their fault because including CSS within packages is a common practice and nothing is wrong with it:

https://github.com/vercel/next.js/issues/10059#issuecomment-607444285

Try this maybe:

https://github.com/vercel/next-plugins/issues/70#issuecomment-474722343

**Comment by danqing** [comment]
Yeah I think it's definitely their fault (or more appropriately, inflexibility of design), though there doesn't seem to be an easy way to work around it :(
