### ISSUE TITLE
loadOriginalValues triggers empty change event

### ISSUE THREAD

**Issue by gpetrov** [yairEO/tagify#538]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

When calling `loadOriginalValues` - it calls inside `removeAllTags` that clears the input and triggers empty change event while the input isn't changed

Related to https://github.com/yairEO/tagify/issues/514

**Comment by yairEO** [comment]
Thanks, it's a known issue and has veen fixed this week and will be deployed shortly

**Comment by gpetrov** [comment]
Tried the latest 3.11.0 - but the problem still happens. Change event is still triggered with empty input because of the **removeAllTags** in **loadOriginalValues** 

After applying the update fix above - it is solved.

**Comment by gpetrov** [comment]
@yairEO this problem still not solved... This issue should be re-opened.
The solution is listed above, but it is still not in the codebase ...

**Comment by gpetrov** [comment]
In the latest code this will be:

https://github.com/yairEO/tagify/blob/master/src/tagify.js#L1402


```js
this.update()
```
to:
```js
this.update({
   withoutChangeEvent: true
})
```

**Comment by gpetrov** [comment]
@yairEO this is still not fixed ... could you please reopen?
it is an issue preventing us to use the latest version.

we don't want a change event in every creation directly - just because tagify inits - nothing has changed!

**Comment by yairEO** [comment]
Hi @gpetrov - Are you calling `loadOriginalValues` yourself, directly? are you passing any parameter?

**Comment by yairEO** [comment]
@gpetrov - do you still need help?

**Comment by gpetrov** [comment]
@yairEO sorry for the delay. 

I do use indeed `loadOriginalValues` on various occasions when needed to load a new tagify value and pass the new value as parameter. When doing so tagify emits two change events - one empty due to `removeAllTags` being called first, and then another one when the given value is set.

I think, when you internally call `removeAllTags` you shoudn't emit a change event.

**Comment by yairEO** [comment]
`removeAllTags` should emit a `change` event since it changes the value to be empty. I cannot change it as you wish because it might break the code for countless others which have been using Tagify for years - if they  update Tagify they might find there is no more `change` event and who knows what problems that might cause..

Why is it so bad a `change` event is called twice for `loadOriginalValues`?

### Possible solutions without me changing any internal code:

1. debounce the event
2. before calling `loadOriginalValues` turn the `change` listener *off*: `tagify.off('change', yourChangeCallback)`
and then turn it back on afterwards
3. Simply not care about multiple `change` events (I must know why does it matter so much how many are called)

**Comment by yairEO** [comment]
I will soon update Tagify's code so `loadOriginalValues` will trigger `removeAllTags` in a way it will not emit the `change` event

**Comment by gpetrov** [comment]
Thank you! That will be great!

Yes we already had a debounce in place - but it feel like a dirty solution.

We are minimizing the changes to the minimum because a lot of actions are executed there to change other parts of the UI and if you have multiple changes so quickly - it breaks. 

And the empty state is not really an outside change but more of an internal clear. So no need for change event for that.
So I'm glad you will be changing it.
