### ISSUE TITLE
validate input

### ISSUE THREAD

**Issue by namnguyen211** [yairEO/tagify#548]
i want input only letter and number, no symbol or special character accept. please help me.thanks

**Comment by yairEO** [comment]
letters in which language?

anyway, you should post such questions in stackoverflow, and better yet, simply search stackoverflow because this isn't related to Tagify, this is basic `input` element [`pattern` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern) regex.

Use it on your original input as so:

    <input pattern="">

Or as a Tagify setting:

```
new Tagify = (..., {
	pattern: ""
})
```
