### ISSUE TITLE
Whitelist with objects does not respect casing

### ISSUE THREAD

**Issue by tavosansal** [yairEO/tagify#567]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Demo Page
https://jsbin.com/yepaweyibi/1/edit?html,js,output

https://soapbox.wistia.com/videos/45uvmPg1tz

### Explanation

- **What is the expected behavior?**
I expect that if the values are the same string but with different casing, then the tags would be treated as separate tags

- **What is happening instead?**
When I pick the tag with the upper case letters, the tag with lower case letters is always selected. 

- **What error message are you getting?**
No errors

**Comment by yairEO** [comment]
Very nice video :) first ever somebody shows me a video with their voice-over. it's a good addition.

I've made the presumption that this scenario will never happen, because in the majority of cases the users do want **case-insensitive** matching (so the first case is chosen in your demo, because it comes before in the *whitelist* array)

I can add a setting to for those who do wish a **case-sensitive** matching.

May I know what is the **real** use-case for this?

**Comment by tavosansal** [comment]
We have some users that have created some crazy tags. So basically you can have a tag for 'SCRUM' and one for 'Scrum'. The use case is silly in my opinion but some of my users are used to this unfortunately :(
