### ISSUE TITLE
Handling tag delete event

### ISSUE THREAD

**Issue by calvma** [yairEO/tagify#578]
Deleting a tag is not removing that tags value dict from the input's value list on change.  Am i missing a step?

1. click on input to add a second tag
![image](https://user-images.githubusercontent.com/22796161/87616304-9e03d980-c6c9-11ea-8f0b-d18ec9e7118a.png)

2. tag added --> console output looks fine
![image](https://user-images.githubusercontent.com/22796161/87616347-ad832280-c6c9-11ea-8cc4-da7a73b2ae51.png)

3. add a third tag --> console output still looking good
![image](https://user-images.githubusercontent.com/22796161/87616380-bc69d500-c6c9-11ea-8a6f-d790403f4bdd.png)

4. delete the original tag --> no change seen by the event listener, hence no output to console
![image](https://user-images.githubusercontent.com/22796161/87616400-c8ee2d80-c6c9-11ea-89a3-3bcc63113e16.png)

5. add a new tag --> the previously deleted tag's value is still in the target list outputted to the console
![image](https://user-images.githubusercontent.com/22796161/87616453-ec18dd00-c6c9-11ea-89eb-6c58ea58fd53.png)

**Comment by yairEO** [comment]
You did not create a demo page, as asked for in the _issue template_ therefor it is impossible for me to help. I don't know your Tagify code & setup and since this problem seems to happen only to you, I would need you to **help me** to *help you*.

Please [clone this demo page](https://jsbin.com/kohonam/1/edit?html,js,output) and try to reproduce the problem

(click on the top-left `"file"` menu and then `"clone"` and make your changes)

**Comment by yairEO** [comment]
@calvma - you still need help?

**Comment by calvma** [comment]
I was able to figure out a work around!

The issue was because I was putting the <tags> element in editable mode with vanilla javascript as soon as the tagify object was created. 

You can definitely close this issue, thanks for all your help!
