### ISSUE TITLE
Tag separator delimiter does not change.

### ISSUE THREAD

**Issue by lordmikefin** [yairEO/tagify#62]
I have problem with tagify field.
( BTW: great js module )

I defined delimiter for tagify.

`	var tagify = new Tagify( input, {`
`		autocomplete        : false,`
`		delimiters          : " ",`
`		duplicates          : false,`
`		whitelist           : ['test', 'foobar'],`
`		callbacks: {`
`			add : onAddTag,`
`			remove : onRemoveTag`
`		}`
`	});`

But this does not change the delimiter for the original field.
So with input tags "test" and "foobar" will result string 'test,foobar' at input field.

I do not use comma at all.

It should be possible to set "original" delimiter for the input field.

**Comment by yairEO** [comment]
The delimiters are meant for user interaction and not the saved value on the original element.

what I mean bu that is that the `delimiters` option's job is to dictate when does a new tag is added when the user is typing or pasting. om your example, your delimiter is a "space" character, so any time the user is hitting the spacebar or is pasting text which contain spaces, the words "between" the spaces become tags.

what you want is a completely different thing. why does it matter to control the delimiters on the value of the original element? can't the server solve whatever the issue is on the server-side?

The `delimiters` setting is a complex which can have more than one delimiter, and then the code couldn't know which one you would like to use for the saved values of the original input..

I believe it's better to keep it using `,` commas and not have it changed. I don't see any possible scenario where the server could not be modify to handle this..

**Comment by andrewschmidt-a** [comment]
This is definitely a valid use case....

**Comment by yairEO** [comment]
@andrewschmidt-a  - https://github.com/yairEO/tagify/issues/1049
