### ISSUE TITLE
Style of box

### ISSUE THREAD

**Issue by vsoch** [yairEO/tagify#708]
Thank you for creating this library, it's really useful! We have a page that uses tagify, and the search box (an input) is eventually changed to a `<tags><span></span></tags>` sort of setup. The issue is that the style on the page, to the viewer, seems to "jump" from an unstyled to the styled box. Is there any way / suggestion to style the original input so the change isn't noticeable?

**Comment by yairEO** [comment]
it depends of how is your code structured. is it React? is it plain vanilla website?

depends how/where tagify script is called, if it's cached.. when is Tagify initialized... where/when Tagify's CSS is loaded... 

If you don't know the answers to these questions then you can simply set

    visibility: hidden

To the CSS of your tags *input* element, and Tagify will simply appear when ready

**Comment by vsoch** [comment]
Thanks for the speedy response! I can definitely answer your questions. We are using tagify in vanilla javascript / css / html, meaning:

 - we have our css for tagify at the [top of the page](https://github.com/yeastphenome/yeastphenome.org/blob/fd833b44276d5093b7083571d109d9e44dc40fd1/yeastphenome/apps/phenotypes/templates/phenotypes/explorer.html#L5) (right within the body tag)
 - the tagify script is called at the end of the body [here](https://github.com/yeastphenome/yeastphenome.org/blob/updates/december-1/yeastphenome/apps/phenotypes/templates/phenotypes/explorer.html#L95) and the setup is just below that.
  
I can definitely set the visibility to None if we can't figure out the above, but ideally we'd have the box just rendered on the page load. If you have some time, could you take a quick look at the file I linked?

**Comment by yairEO** [comment]
There is `none` value for `visibility`, but `hidden`

The second link is `404` but I can guess it's also from a CDN.

Your app is not SSR (server-side-render), therefore *Tagify* will only be applied on the input element once the Tagify script & CSS have been downloaded & parsed. Since the script tag is at the end of the `<body>` tag, then the page will load and only afterwards the script. you can move the script to the `<head>` section of the HTML page and then it will be available before the page, and hopefully the Tagified input will appear immediately as you intend it to be.

Or... simply hide (using `visibility` CSS property) the input and let tagify show itself whenever it's ready

**Comment by vsoch** [comment]
> Your app is not SSR (server-side-render), therefore Tagify will only be applied on the input element once the Tagify script & CSS have been downloaded & parsed. Since the script tag is at the end of the <body> tag, then the page will load and only afterwards the script. you can move the script to the <head> section of the HTML page and then it will be available before the page, and hopefully the Tagified input will appear immediately as you intend it to be.

I'll give that a shot, and let you know if it works!

**Comment by vsoch** [comment]
okay, the second option worked best - basically hiding the input until tagify loads it (moving to the head seemed to break things, because there is a lot of parsing that I think depends on having some of the page loaded). Thanks for your help @yairEO, closing issue!
