### ISSUE TITLE
Issue with dropdown on Firefox

### ISSUE THREAD

**Issue by kermanf** [yairEO/tagify#715]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
Can't really provide a demo because I'm using the lib in Chrome extension, it works ok in browser.

### Explanation

- **What is the expected behavior?**
The dropdown should appear above the tagify component if there is not space under it and it works ok in Chrome.

- **What is happening instead?**
In Firefox it extends the popup window making it scrollable but when you hover an option it twitches and shows the dropdown on the top side for a millisecond and then it shows the dropdown again on bottom.

- **What error message are you getting?**

**Comment by yairEO** [comment]
Please make a demo page (at jsbin.com) and reconstruct the situation so I could examine, since I have no idea where is your tagify located, how the whitelist looks like and what is your configuration. Since I've never seen this bug, it must be something specifically in your set up, which I must see

**Comment by yairEO** [comment]
still need assistance?

**Comment by kermanf** [comment]
hey, sorry for the late reply, yes i still haven't figured out what is causing the issue. It is hard for me to reproduce it since it is in web extension. On chrome it works ok and the dropdown has placement top, but the issue still exists in firefox and safari.

**Comment by kermanf** [comment]
Hey, here is a screen record of the bug if it will help: 
![image](https://user-images.githubusercontent.com/32766979/103994911-f8bd5000-5197-11eb-80d1-58182bc9c8f8.png)

**Comment by kermanf** [comment]
Here is a screen record of the bug if it will help.

https://user-images.githubusercontent.com/32766979/103995022-21454a00-5198-11eb-91ce-2e3bd59caeae.mov

**Comment by kermanf** [comment]
This is an example of my Tagify component in React

```javascript
const TagInput = <T,>({ options = [], value, onChange, ...rest }: Props<T>) => {
  const tagifyRef = useRef() as MutableRefObject<T | any>;
  return (
    <Box className="new-link__labels">
      <Tags
        settings={{ dropdown: { enabled: 0 } }}
        tagifyRef={tagifyRef}
        whitelist={options}
        onChange={useCallback(() => onChange(tagifyRef.current.value), [])}
      />
    </Box>
  );
};
```

**Comment by yairEO** [comment]
I see the problem. I will examine

**Comment by kermanf** [comment]
Thanks for a quick response!

**Comment by kermanf** [comment]
@yairEO Hello, just wanted to know if you have any update on this. Thanks!

**Comment by yairEO** [comment]
No... I had other issues with my other open-source packages..

is this important to your company?

**Comment by kermanf** [comment]
Yeah, kinda. We can't publish the firefox extension because of the issue.

**Comment by yairEO** [comment]
Maybe your company would like to donate to my effort in this project so I would be more motivated to spare the time to help with this? It looks like it would take a while to solve since it's related in a part of the code I haven't touched in a long time, about 3 hours I would say

**Comment by yairEO** [comment]
I cannot seem to reproduce it in Firefox.. as you can see, Tagify is at the bottom of the page:

https://jsbin.com/qogirun/2/edit?html,css,js,output

Maybe it's because you are inside an iframe.. can you try to make a *reproducible* demo for me to examine?

**Comment by ivanbozic** [comment]
Hey @yairEO, one of the founders of the company mentioned above. Thank you for the library and we're definitely interested in donating for your efforts.

We discussed a bit internally and we have two options:

- We can try and get a reproducible demo of the issue, but it's convoluted since it's inside of a Chrome extension and we couldn't reproduce the issue with just a basic `<iframe>`.
- The other option is to add support for a `position` (as an example) prop to the library so that instead of the library positioning itself automatically, we can force it to always show above or below of the field that it is linked to. For our use case, it would actually always work better this way.

Thoughts? Also let me know on best way to proceed with donations. 😊

**Comment by yairEO** [comment]
@ivanbozic - As I wrote in the [settings section](https://github.com/yairEO/tagify#settings) for the `dropdown.position`, it allows the value of `manual`, therefore enabling you as the developer to positioning it yourself, and with just a little big of code, it's fairly easy to have it always "open" above your component and not at "under" it. 

Here's a demo for it:
https://yaireo.github.io/tagify/#section-manual-suggestions

Thank you for wanting to donate for my open-source efforts :)
I really appreciate that, since I do open-source full-time and nobody ever pays and I never ask..
My PayPal: vsync.design@gmail.com

👾👔

**Comment by yairEO** [comment]
Hi @ivanbozic - I've created a new setting which might be useful to you:

https://github.com/yairEO/tagify/issues/754#issuecomment-786188479
