### ISSUE TITLE
Unable to insert tag containing "<x>" with tab key

### ISSUE THREAD

**Issue by RichardD2** [yairEO/tagify#733]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsfiddle.net/RichardD/9a8g7sv2/1/

### Explanation
Type `cc`, press down-arrow to select `cc <c>`, and press `Tab` to insert the selected tag.

#### Expected behaviour
The tag `cc <c>` is inserted.

#### Actual behaviour
The tag `cc` is inserted. The ` <c>` suffix is lost.

#### Additional
Selecting any of the other tags - `aa`, `bb (b)`, `dd <`, `ee >`, or `ff <>` - works as expected.

Selecting the problem tag with the mouse works as expected.

Tested in Firefox 85 and Chrome 88.

No errors are shown in the console.

**Comment by yairEO** [comment]
![GIF](https://user-images.githubusercontent.com/845031/107286874-d609aa00-6a69-11eb-8168-8978ee67de95.gif)
 
cannot reproduce

**Comment by RichardD2** [comment]
As I said, selecting the tag with the mouse works fine. Selecting the tag with the keyboard doesn't.

**Comment by yairEO** [comment]
it's because your string `cc <c>` contains something which looks like an HTML tags (`<c>`) which is then gets ignored by the browser when the innerHTML of the input is set.

For example, if you try:

    tagify.DOM.input.innerHTML = "ccc <xx>"

it wouldn't work.

I will escape it internally before setting the innerHTML and push the new version soon, you will see this issue closed when it's done
