### ISSUE TITLE
When multiple classes are assigned to the classNames.input, an error occurs

### ISSUE THREAD

**Issue by NullVoxPopuli** [yairEO/tagify#738]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/kakagisovu/edit?html,js,output

### Explanation

- **What is the expected behavior?**

No error

- **What is happening instead?**

Error

- **What error message are you getting?**

```
Uncaught TypeError: this.DOM.input is null
    binding https://unpkg.com/@yaireo/tagify:1
    f https://unpkg.com/@yaireo/tagify:1
    <anonymous> jekuqap.js:38
```

**Comment by yairEO** [comment]
why are you adding classes to the `input` element specifically and not to the wrapper itself? 

You can add the classes afterwards:

    tagify.DOM.input.classList.add(...)
    
Currently you cannot add multiple class names to the input field in the way you are trying to, since I never imagined someone will change the input's class, and if so, override it with multiple class names.. it's not easy to solve this now that the code is mature

**Comment by NullVoxPopuli** [comment]
> why are you adding classes to the input element specifically and not to the wrapper itself?

cause that's how use use Tailwind. No CSS. :shrug:

**Comment by NullVoxPopuli** [comment]
> You can add the classes afterwards:

how would that work with `dropdownItem`, `dropdownItemActive`, and `tag`?, since those things are dynamic?

**Comment by yairEO** [comment]
Why can't you just write CSS? 

Anyway, you should not override Tagify's default class names, but simply write your own CSS which overrides the default Tagify's CSS file 

You cannot add multiple class names currently, it is not designed to support that, and it is also not a limiting factor since you can write CSS but actively chose not to
