### ISSUE TITLE
Tiny change to support Server Side Rendering (Next.js etc)

### ISSUE THREAD

**Issue by defucilis** [yairEO/tagify#758]
On line 209 of tagify.min.js, there's this line:

```js
var isChromeAndroidBrowser = /(?=.*chrome)(?=.*android)/i.test(navigator.userAgent);
```

`navigator` is undefined when running on the server, which means that tagify can't be used 'normally' in this context (needs to be dynamically imported, which is suboptimal for a bunch of reasons)

The following replacement fixes it just fine:

```js
var isChromeAndroidBrowser = false;
try {
  isChromeAndroidBrowser = /(?=.*chrome)(?=.*android)/i.test(navigator.userAgent);
} catch {}
```

and as far as I can imagine couldn't introduce any problems, since navigator is only undefined in the browser, in which case it doesn't matter whether we're in chrome android browser or not.

**Comment by yairEO** [comment]
Thanks for shining light on SSR issue, I will fix it, but in a different way since I don't understand how can the code you showed helps since - it will always be `false` since the `try` block will always fails due to inexistence of `navigator` while the code evaluates. I will replace it with a function instead
