### ISSUE TITLE
How to use addTags onclick event?

### ISSUE THREAD

**Issue by accesstechnology-mike** [yairEO/tagify#763]
I'm trying to create a set of predetermined tags as suggestions for tags under my input field, but I can't get the addTags function to work with an onclick event:

`<button onclick="myFunction()">Click me.</button>`

```
  function myFunction() {
      addTags(["banana", "orange", "apple"])
    }
```

Either addTags is not defined (when outside the tagify script, or myFunction is not defined when within it.

**Comment by accesstechnology-mike** [comment]
I managed to get this working with jquery (example here: https://stackoverflow.com/questions/59357458/tagify-set-data-in-tagify-input-on-click) but I'd rather not add another library if possible

**Comment by yairEO** [comment]
Obviously `addTags` is not defined since you call as a global function which is on the global Window scope. In javascript you must call a function where it's defined, and since Tagify is a library, it has methods, which `addTags` is one of them, and therefore you need to call the method where it is defined:

```js
var tagify = new Tagify(...)

...your code, whatever it is...

function myFunction() {
   tagify.addTags(["banana", "orange", "apple"])
}
```
