### ISSUE TITLE
Adding tags without trigger add event

### ISSUE THREAD

**Issue by mikeazores** [yairEO/tagify#774]
Hi! The removeTags function has a silent parameter that avoids triggering the "remove" event.
I checked addTags and there is no similar parameter. Is that any way of adding a tag without triggering the "add "event?

I'm inserting and removing the tags from tagify on server side listening to remove and add events in tagify. However, if some insert or delete operation in server is not successful, in order to keep the displayed tags synched with the server, I need to add or remove them accordingly without trigger the events (to avoid loops).

**Comment by yairEO** [comment]
Hi

For removing tags I suggest you to use the [Tagify hook](https://github.com/yairEO/tagify#hooks) `beforeRemoveTag` and if the deletion operation failed on the server, simply reject the promise, and the tag will remain.

For adding a tag which failed to be added on the server, there is no hook because I thought the developer would simply remove that tag, and although that will trigger a "remove" event listener, which will cause a server request (for a non-existing tag to be removed) I don't see any problem that might happened because of this flow.

Also, I discourage syncing the server with changes from `add` and `remove` events and start using the `change` event, because it makes more sense to save the whole value of the field, as-is, on any change, rather than a single tag at a time, and to deal with "delete/add/edit" flows.

Simply send the whole value to the server and have it re-write it to the DB

**Comment by mikeazores** [comment]
> Hi
> 
> Also, I discourage syncing the server with changes from `add` and `remove` events and start using the `change` event, because it makes more sense to save the whole value of the field, as-is, on any change, rather than a single tag at a time, and to deal with "delete/add/edit" flows.
> 
> Simply send the whole value to the server and have it re-write it to the DB

Thanks a lot. It makes all the sense to save all the tag values at once to the server. I will do that!

**Comment by yairEO** [comment]
At the end Tagify is just a complex way to *visually* simplify typing tags manually to a plain `<input type="text">` DOM element, and therefore should be treated the same - when the input's text changes, the input's `value` is sent to the server, as-is
