### ISSUE TITLE
Enhancement: keep & highlight invalid input 

### ISSUE THREAD

**Issue by yaalaa** [yairEO/tagify#78]
Is it possible not to remove invalid input? 
Instead, to keep it and highlight (with _red_ color, for instance).

**Comment by yairEO** [comment]
Does this request also requires the invalid tags to be added to the original input's value (as a String) and be sent to the server? or is this only a visual thing, to keep them on the screen & ignoring them technically

**Comment by yairEO** [comment]
Ok, made some changes. check it out in the (demo page)[https://yaireo.github.io/tagify/#section-advance-options]

**Comment by yaalaa** [comment]
Just seen. Nope. 
I mean this:
- user types something which doesn't match pattern
- user presses `<enter>` or types a delimiter
- neither the text disappears nor new tags appear,
- instead, the text remains at `input` and colored red indicating it's not valid for tag
- there might be a callback notifying user has typed something inappropriate (surrounding UI might show a tooltip describing the rules)

With the current behavior the text which is not suitable for tag simply disappears.
It would nice to have a option to switch to the scenario I've described above.
It would give user a chance to recognize his mistake and correct the text.
How do you think?

**Comment by yairEO** [comment]
yes, the only problem is that the user can have the original input pre-filled with some value, and parts of that value are invalid tags. Also, a user can paste a bunch of tags and some will not be valid.. therefor it won't be much beneficial in terms of UX to do as you suggested. 

I only makes sense when tags are being inserted one by one

**Comment by yaalaa** [comment]
At least, there could be an option to enabled _neck or nothing_ behavior, i.e. to apply if there are only valid tags or not to apply at all.
See for yourself.
I'd just say it's annoying a bit when you have typed an invalid sequence (one wrong symbol) and it disappears as soon as you type a delimiter or hit `<enter>`.

**Comment by yairEO** [comment]
I've added a class `tagify__input--invalid` to the `contenteditable` element which serves as Tagify's input, and that class is added while the user is typing, if the value does not pass validations.

You, as the author of your program, can use this class to mark signal the user that their input is invalid. for example, you can give a red color to the `contenteditable` (for that class).

I didn't include a red color in the demo because I don't think it looks good.
I was hesitant on disallowing the user to enter a tag simply because it is invalid, but rather give the users clues, as they type, if the input is OK to go.
