### ISSUE TITLE
Internet Explorer 11 fails on jQuery.tagify.min.js since 3.16

### ISSUE THREAD

**Issue by krzyko** [yairEO/tagify#811]
Good day,

I've got an error using IE11 with jQuery.tagify.min.js which originate back to tagify 3.16 version.

SCRIPT1006: ')' Expected
jQuery.tagify.min.js (3,37)

IE11 as a non-ES6 browser fails at function's parameter default value. Using polyfill doesn't help at all.

Regards,
Krzysztof Kosz.

**Comment by yairEO** [comment]
It appears IE11 usage statistics has dropped in 2021 to be less than `1%`, therefore Babel did not compile the code to support IE11.

```js
"browserslist": [
    ">1%",             // <----
    "not dead",
    "not ie < 11",
    "not IE_Mob 11",
    "not op_mini all"
]
```

I think it's for the best not to support IE11 and let those very few folks who still use it to have the web break in front of their eyes and understand the time has come to upgrade or suffer the consequences.

**Comment by krzyko** [comment]
Good day,

Browserslist default is 0,5% market share: [https://github.com/browserslist/browserslist#full-list]. I know that IE11 is old and all other browsers are better, but there are places where it has even more market share. And still it is supported by the vendor.

I'm not asking for daunting chore, bot only for two changes in gulpfile - to lower browser cut-off threshold from 1% to 0.5% and to replace https://github.com/yairEO/tagify/blob/master/gulpfile.js#L25 in the jquery wrapper from:
`    $.fn.tagify = function(settings = {}){ `
to:
`    $.fn.tagify = function(settings){
        settings = settings || {};`

Regards,
Krzysztof Kosz.

**Comment by yairEO** [comment]
May I know in what is your product to understand why IE11 support is so important for it?

Browserslist default always has been `1%`, not `0.5%`, I have no idea why you're saying that or perhaps it was changed to `0.5%` very recently without me being notified.

Skipping support for IE11 allows Tagify script to shed some weight, which is a good thing, and you are asking me to add back that weight, which is a negative thing for the other ~99.3% other users... I need a good reason for that

**Comment by pascalalfadian** [comment]
Hi! I am joining this conversation because I have similar situation. In my case, I am using the library to make a nationwide competition portal for both arts and debate in Indonesia. That includes students living in some remote and poor areas, with their cheap or knockoff smartphones. Last year I received reports of students failed to participate because the JavaScript simply didn't work in their phone, so I am trying as much as I can do to cover more and more devices. Having my website supporting IE gives me confidence that it should work in those cheap phones.

Having said all that, I completely understand @yairEO decision to stop supporting older browsers. In my case, I may be able to custom patch the library at a cost of a few kilobytes more for my users.

Thanks.

**Comment by yairEO** [comment]
Hi @krzyko - yes, best to replace links in `package.json`, but I don't see what will you gain from all this effort. 

You are helping so little people and putting to much work into it, that it is not worth it. very not economical
