### ISSUE TITLE
Slicing of JSON string in update method

### ISSUE THREAD

**Issue by binzmrc** [yairEO/tagify#82]
Hey,

Is there a purpose on slicing the JSON string that becomes the value of the original hidden input?
It currently strips the brackets of the JSON.stringify result. Therefore I am not able to parse the JSON server-side. On the other hand, I cannot explode the string by comma, because due to JSON.stringify additional quotes were added around the tags.

I mean, yes, I can simply change this behavior, but I thought it could be a bug...
So if this is intended, it would be great if you could explain it to me.
Otherwise may I commit a pull request?

Thanks in advance,
Marc

**Comment by MiChAeLoKGB** [comment]
This one annoyed me too and forced me to explode the result by comma and then trim the quotes. 
Or a simpler method to deal with it would be to just add `{` and `}` back server side and parse it as a JSON 😅

I can't really find a single reason, why it shouldn't be returned as a valid JSON. Its much easier to work with server side, than comma separated list of quoted strings.
Maybe its like that because that code was just copy pasted from SO? 🤔

**Comment by yairEO** [comment]
@MiChAeLoKGB  -  It's an Array, not an Object, so adding `{` & `}` is not what you want, but probably `[` & `]`.

I would suggest, as others had asked before in the issues, to not use the input's value but use tagify's value instead:

    var tagify = new Tagify(...);
    // use this when sending your form's AJAX data:
   //  tagify.value

I will change the input's value to be a String representation of an Array

**Comment by AndryHTC** [comment]
So... Are there any ways to use the serialize function of jQuery, obtaining a comma separated string?
