### ISSUE TITLE
Documentation Code Block Display Issue

### ISSUE THREAD

**Issue by chuyunshen** [yairEO/tagify#858]
Hi there,

I noticed that the documentation is not displaying a JavaScript code block properly.
<img width="1280" alt="Screen Shot 2021-07-11 at 4 33 38 PM" src="https://user-images.githubusercontent.com/44233890/125209437-b2d86600-e266-11eb-8aa8-af1aee20fdae.png">

I can see the correctly formatted code example if I proceed with the CodePen link or check the index.html from the repository.
I can reproduce this issue in Chrome and Firefox.

**Comment by yairEO** [comment]
Yeah I know, it is a bug with the syntax highlight `prism.js`, Maybe they fixed it already, I will check. It's an old bug they did not solve and I gave up since I couldn't find any other decent syntax highlighter at the time. 

I will look into it, but this is not that important since you can see the exact same code if you click the *Codepen* Icon at the center, between the code block and the actual rendered example

**Comment by yairEO** [comment]
Fixed it now, after 3 years. Thanks for giving me the motivation by complaining about it! 

Please feel free to complain about more things and write it all here

**Comment by chuyunshen** [comment]
Thanks for the fix and the prompt response! This will make it clearer for the new users of this awesome tool. I personally was confused until I checked the CodePen link :D
