### ISSUE TITLE
Initial value differs from the library generated value

### ISSUE THREAD

**Issue by melenaos** [yairEO/tagify#87]
When I render the input that will be tagified the value doesn't contain any quotes:
`<input name='tags' class='some_class_name' placeholder='write some tags' value='css, html, javascript, css' autofocus>`

But when I read the value from the input then every tag is wrapped into double quotes:
`$('input.some_class_name').val()`
`"\"css\",\"html\",\"javascript\""`

Please note that this only happens if you add or remove a tag, that means that if the value is altered by the **tagify** library.

This causes problem because I read the input value, i store it in my DB and when i rerender the input then new characters are added in the input `\"`

This was not an issue with the version `1.2.0`, it appeared after my try to upgrade to `2.1.0`

**Comment by yairEO** [comment]
I know, this is a serious problem which one need to take into account when submitting a form. you need to send the data using ajax directly from Tagify API and not rely on the input itself.

the problem is that tags might include commas, for example location tags: "new york, NY"

this required me to escape each tag in the way you have showed, so it will be clear when a tag starts and ends.

Do you have perhaps a better idea to tackle this problem?

**Comment by melenaos** [comment]
I couldn't input `New York, NY` because it splits it into two tags `New York` and `NY`. Is there any special way of inputting comma? 

Maybe you can escape the comma character (e.g. `\,`) or change the separator (e.g. `\n`).

**Comment by yairEO** [comment]
the default setting is to split input into tags by comma, so you'll need to change the setting. 

See README file for details at the bottom.

If i replace the original commas as you suggested, then the server will have to replace them again back to commas, and that is a big thing to ask from users.

best to send your tags data directly from tagify and not from the input itself

**Comment by melenaos** [comment]
Nice, as I saw I can use the `tagify.value` to get the values. But this is an array so should I `String.Join` them to get it as I want?
