### ISSUE TITLE
Pasting inserts text in wrong position, and moves caret

### ISSUE THREAD

**Issue by ruaridhnewman** [yairEO/tagify#890]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
Paste some text at the end of the first field in this demo page
https://jsbin.com/yalucil/edit?html,js,output

### Explanation

- **What is the expected behavior?**
When I paste some text into a mixed mode tagify input which already has some text in it, the text should appear where the caret is, and the caret should be set to the end of the pasted text.

- **What is happening instead?**
On firefox - the pasted text appears at the start of the input, regardless of whether there is already some text in the input.
On chrome - the pasted text appears in the correct place, but the caret is then moved back to the start of the input text.

- **What error message are you getting?**
N/A

#### Firefox

https://user-images.githubusercontent.com/26965443/130070019-53835407-6cdf-4dcd-a46e-ba685a9c79dd.mov

#### Chrome

https://user-images.githubusercontent.com/26965443/130070262-636fde6b-5ee6-4d8f-a14a-b6bce2231d4a.mov

**Comment by yairEO** [comment]
You are doing something that is out of the ordinary: `tagify.loadOriginalValues()` when pasting, so obviously the caret will loose focus since the whole content is replaced...

Obviously this line is causing the specific issues you ate facing so what can be done? of course the first go-to would be placing it inside a `setTimeout` and inspect how it behaves:

    setTimeout(tagify.loadOriginalValues,0)
    
    
Seems to have solved everything :)
