### ISSUE TITLE
Current package.json shows 4.9.2 but npm has 4.9.3 and 4.9.4

### ISSUE THREAD

**Issue by dirslashls** [yairEO/tagify#965]
How is this possible? I actually updated my dependency to 4.9.4 and then noticed that in single-select mode the height of the widget is more than it should be. Reverting it to 4.9.2 worked fine but then I noticed this discrepancy. It seems that 4.9.3 and 4.9.4 are published on 12/11/2021 within a few minutes gap.

**Comment by yairEO** [comment]
Yes I saw this also, I don't know also what happened, but the problem is only with the number itself, as the versions are the same.

I am using the `np` package to automate the releases and I've written an article about it (if you're interested):

https://dev.to/yaireo/automate-npm-package-publish-git-versioning-5cfp

On the next release the versions will be aligned, I just haven't had the time to push anything in the last few weeks
